import {
  Aperture,
  Boxes,
  Brain,
  Camera,
  ChartColumn,
  Clapperboard,
  Cloud,
  Code,
  Cpu,
  Database,
  Eye,
  Focus,
  Gauge,
  Grid2x2,
  Image,
  Layers,
  Microscope,
  Milestone,
  Network,
  Orbit,
  Rocket,
  Scan,
  ScanEye,
  Shapes,
  Sparkles,
  Spline,
  Target,
  Trophy,
  Video,
  Waves,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  code: Code,
  grid: Grid2x2,
  chart: ChartColumn,
  brain: Brain,
  image: Image,
  waves: Waves,
  scan: Scan,
  aperture: Aperture,
  layers: Layers,
  network: Network,
  target: Target,
  rocket: Rocket,
  database: Database,
  shapes: Shapes,
  gauge: Gauge,
  wrench: Wrench,
  "scan-eye": ScanEye,
  zap: Zap,
  spline: Spline,
  video: Video,
  sparkles: Sparkles,
  focus: Focus,
  boxes: Boxes,
  clapperboard: Clapperboard,
  eye: Eye,
  milestone: Milestone,
  orbit: Orbit,
  microscope: Microscope,
  cpu: Cpu,
  cloud: Cloud,
  camera: Camera,
  trophy: Trophy,
};

export function nodeIcon(icon: string): LucideIcon {
  return ICONS[icon] ?? Target;
}
