import {
  Aperture,
  BookOpen,
  Briefcase,
  Building,
  Calculator,
  Cog,
  FileText,
  FlaskConical,
  Globe,
  GraduationCap,
  Hammer,
  HeartPulse,
  Landmark,
  Lightbulb,
  PenTool,
  Route,
  Scale,
  Stethoscope,
  Users,
  Boxes,
  Brain,
  Camera,
  ChartColumn,
  Clapperboard,
  Cloud,
  Code,
  Cpu,
  Database,
  Eye,
  Focus,
  Gauge,
  Grid2x2,
  Image,
  Layers,
  Microscope,
  Milestone,
  Network,
  Orbit,
  Rocket,
  Scan,
  ScanEye,
  Shapes,
  Sparkles,
  Spline,
  Target,
  Trophy,
  Video,
  Waves,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  code: Code,
  grid: Grid2x2,
  chart: ChartColumn,
  brain: Brain,
  image: Image,
  waves: Waves,
  scan: Scan,
  aperture: Aperture,
  layers: Layers,
  network: Network,
  target: Target,
  rocket: Rocket,
  database: Database,
  shapes: Shapes,
  gauge: Gauge,
  wrench: Wrench,
  "scan-eye": ScanEye,
  zap: Zap,
  spline: Spline,
  video: Video,
  sparkles: Sparkles,
  focus: Focus,
  boxes: Boxes,
  clapperboard: Clapperboard,
  eye: Eye,
  milestone: Milestone,
  orbit: Orbit,
  microscope: Microscope,
  cpu: Cpu,
  cloud: Cloud,
  camera: Camera,
  trophy: Trophy,
  // Non-CS disciplines (keep in sync with ROADMAP_ICONS in services/api/app/schemas.py).
  book: BookOpen,
  scale: Scale,
  stethoscope: Stethoscope,
  heart: HeartPulse,
  briefcase: Briefcase,
  graduation: GraduationCap,
  calculator: Calculator,
  flask: FlaskConical,
  pen: PenTool,
  users: Users,
  route: Route,
  file: FileText,
  building: Building,
  globe: Globe,
  landmark: Landmark,
  hammer: Hammer,
  cog: Cog,
  lightbulb: Lightbulb,
};

export function nodeIcon(icon: string): LucideIcon {
  return ICONS[icon] ?? Target;
}
