#!/usr/bin/env node
/* Generates tools/extract-console.js from src/ so the console snippet runs the exact
 * extension pipeline. Run after editing src/: node tools/build-console.js
 * --check exits 1 if the committed snippet is stale.
 */
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
// Normalise CRLF (Windows checkouts) so output and --check are line-ending independent.
const lf = (t) => t.replace(/\r\n/g, "\n");
const parts = ["src/bb-utils.js", "src/bb-model.js", "src/ics.js", "src/extractor.js"]
  .map((f) => `// ---- ${f} ----\n${lf(fs.readFileSync(path.join(root, f), "utf8"))}`);

const header = `/* IAU Blackboard console extractor — GENERATED by tools/build-console.js from src/. Do not edit.
 * Paste into DevTools on a logged-in https://vle.iau.edu.sa/ultra tab. GET requests only.
 * Options (set before pasting): window.BB_EXTRACT_OPTIONS = { scope: "current"|"all", redact: false, captureSamples: false }
 */
(async function () {
const module = undefined; // force browser globals in the bundled files
`;
const footer = `
const opts = Object.assign({ scope: "current", redact: false }, window.BB_EXTRACT_OPTIONS || {});
const data = await BBExtractor.extractAll({ ...opts, origin: location.origin, onProgress: (m) => console.log("[BB]", m) });
const s = data.summary;
console.log("[BB] Courses: " + s.courses_current + " current / " + s.courses_total + " total · Assessments: " + s.assessments + " · Upcoming: " + s.upcoming_deadlines + " · Overdue: " + s.overdue + " · Announcements: " + s.announcements + " · Grades: " + s.grades + " · Events: " + s.events + " · Content: " + s.content + " · Failed sources: " + s.failed_sources);
const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
const a = document.createElement("a");
a.href = URL.createObjectURL(blob);
a.download = "iau-blackboard-export-" + new Date().toISOString().slice(0, 10) + ".json";
a.click();
setTimeout(() => URL.revokeObjectURL(a.href), 5000);
return data;
})();
`;
const out = header + parts.join("\n") + footer;
const target = path.join(root, "tools/extract-console.js");
if (process.argv.includes("--check")) {
  const current = fs.existsSync(target) ? lf(fs.readFileSync(target, "utf8")) : "";
  if (current !== out) { console.log("stale: run node tools/build-console.js"); process.exit(1); }
  console.log("extract-console.js up to date");
} else {
  fs.writeFileSync(target, out);
  console.log("wrote tools/extract-console.js");
}
