/* IAU Blackboard console extractor — GENERATED by tools/build-console.js from src/. Do not edit.
 * Paste into DevTools on a logged-in https://vle.iau.edu.sa/ultra tab. GET requests only.
 * Options (set before pasting): window.BB_EXTRACT_OPTIONS = { scope: "current"|"all", redact: false, captureSamples: false }
 */
(async function () {
const module = undefined; // force browser globals in the bundled files
// ---- src/bb-utils.js ----
/* BB shared utilities: safe HTML/text, rich-text extraction, timestamps, fetch helpers.
 * No Blackboard-specific endpoint paths here. Works in browser content scripts and Node.
 * Read-only helpers only; never stores credentials.
 */
(function (global) {
  "use strict";

  function isPlainObject(v) {
    return v !== null && typeof v === "object" && !Array.isArray(v);
  }

  // Extract usable text/HTML from Blackboard rich-text fields, which may be a
  // string OR an object (BbML payloads). Never returns "[object Object]".
  // Returns { text, html } where html is the original markup when identifiable.
  function extractRichText(value) {
    if (value == null) return { text: null, html: null };
    if (typeof value === "string") {
      const s = value.trim();
      return { text: s || null, html: looksLikeHtml(s) ? s : null };
    }
    if (Array.isArray(value)) {
      for (const item of value) {
        const r = extractRichText(item);
        if (r.text) return r;
      }
      return { text: null, html: null };
    }
    if (isPlainObject(value)) {
      // Collect plain text AND markup separately: Blackboard objects often
      // carry both (e.g. { rawText: "...", displayText: "<p>...</p>" }).
      let text = null;
      let html = null;
      for (const k of ["rawText", "plainText", "displayText", "text", "message", "value", "content", "html", "body"]) {
        if (value[k] == null) continue;
        const r = extractRichText(value[k]);
        if (!r.text) continue;
        if (!text) text = r.text;
        if (!html && r.html) html = r.html;
        else if (!html && typeof value[k] === "string" && looksLikeHtml(value[k])) html = value[k];
        if (text && html) break;
      }
      if (text) return { text, html };
      // Last resort: first string-valued property (avoids String(obj)).
      for (const k of Object.keys(value)) {
        if (typeof value[k] === "string" && value[k].trim()) {
          const s = value[k].trim();
          return { text: s, html: looksLikeHtml(s) ? s : null };
        }
      }
      return { text: null, html: null };
    }
    // Numbers/booleans: stringify safely (never an object).
    return { text: String(value), html: null };
  }

  function looksLikeHtml(s) {
    return typeof s === "string" && /<[a-z][\s\S]*>/i.test(s);
  }

  const ENTITIES = { "&nbsp;": " ", "&amp;": "&", "&lt;": "<", "&gt;": ">", "&quot;": "\"", "&#39;": "'", "&apos;": "'" };
  const BREAK = "\u0001";

  // HTML -> readable plain text. Block tags become line breaks; runs of spaces collapse.
  function htmlToText(html) {
    if (html == null) return null;
    if (typeof html !== "string") {
      const r = extractRichText(html);
      html = r.text;
      if (html == null) return null;
    }
    const marked = String(html).replace(/<br\s*\/?>/gi, BREAK).replace(/<\/(p|div|li|h[1-6]|tr|ul|ol)>/gi, BREAK);
    let raw = null;
    try {
      if (typeof document !== "undefined" && document.createElement) {
        const div = document.createElement("div");
        div.innerHTML = marked;
        raw = div.textContent || "";
      }
    } catch { raw = null; }
    if (raw == null) {
      raw = marked.replace(/<[^>]+>/g, " ").replace(/&(nbsp|amp|lt|gt|quot|#39|apos);/g, (m) => ENTITIES[m] || m);
    }
    const lines = raw.split(BREAK).map((s) => s.replace(/[\s ]+/g, " ").trim()).filter(Boolean);
    return lines.length ? lines.join("\n") : null;
  }

  // Normalize timestamps to ISO 8601 UTC with millis. Preserves the instant;
  // does not invent a timezone. Returns null when unparseable.
  function normalizeTimestamp(value) {
    if (value == null) return null;
    if (value instanceof Date) {
      const t = value.getTime();
      return Number.isNaN(t) ? null : value.toISOString();
    }
    if (typeof value === "number") {
      // Heuristic: seconds vs millis.
      const ms = value < 1e12 ? value * 1000 : value;
      const d = new Date(ms);
      return Number.isNaN(d.getTime()) ? null : d.toISOString();
    }
    if (typeof value === "string") {
      const s = value.trim();
      if (!s) return null;
      // YYYYMMDDTHHMMSSZ (ICS basic format, possibly without Z)
      let m = s.match(/^(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})(Z)?$/);
      if (m) return `${m[1]}-${m[2]}-${m[3]}T${m[4]}:${m[5]}:${m[6]}.000Z`;
      // YYYYMMDD (ICS DATE)
      m = s.match(/^(\d{4})(\d{2})(\d{2})$/);
      if (m) return `${m[1]}-${m[2]}-${m[3]}T00:00:00.000Z`;
      const d = new Date(s);
      return Number.isNaN(d.getTime()) ? null : d.toISOString();
    }
    return null;
  }

  function sleep(ms) {
    return new Promise((r) => setTimeout(r, ms));
  }

  function isTransientStatus(status) {
    return status === 429 || (status >= 500 && status <= 599);
  }

  // GET with timeout + retries for transient failures (429/5xx, timeouts).
  // Never logs or returns request headers/cookies.
  async function getJson(origin, path, opts = {}) {
    const timeoutMs = opts.timeoutMs || 20000;
    const retries = opts.retries != null ? opts.retries : 2;
    let lastError = null;
    for (let attempt = 0; attempt <= retries; attempt++) {
      const ctrl = new AbortController();
      const t = setTimeout(() => ctrl.abort(), timeoutMs);
      try {
        const res = await fetch(origin + path, {
          method: "GET",
          credentials: "include",
          headers: { Accept: "application/json" },
          signal: ctrl.signal
        });
        if (!res.ok) {
          const err = new Error(`GET ${path} -> HTTP ${res.status}`);
          err.status = res.status;
          if (isTransientStatus(res.status) && attempt < retries) {
            lastError = err;
            await sleep(Math.min(1000 * 2 ** attempt, 5000));
            continue;
          }
          throw err;
        }
        const ct = res.headers.get("content-type") || "";
        if (ct.includes("json")) return await res.json();
        const text = await res.text();
        try {
          return JSON.parse(text);
        } catch {
          throw new Error(`GET ${path} returned non-JSON`);
        }
      } catch (e) {
        if (e && e.name === "AbortError" && attempt < retries) {
          lastError = new Error(`GET ${path} timed out`);
          await sleep(Math.min(1000 * 2 ** attempt, 5000));
          continue;
        }
        if (e && e.status && !isTransientStatus(e.status)) throw e;
        if (attempt >= retries) throw e;
        lastError = e;
        await sleep(Math.min(1000 * 2 ** attempt, 5000));
      } finally {
        clearTimeout(t);
      }
    }
    throw lastError || new Error(`GET ${path} failed`);
  }

  async function pagedGet(origin, pathTemplate, opts = {}) {
    const limit = opts.limit || 100;
    const maxPages = opts.maxPages || 10;
    const out = [];
    let offset = 0;
    for (let page = 0; page < maxPages; page++) {
      const sep = pathTemplate.includes("?") ? "&" : "?";
      const path = `${pathTemplate}${sep}limit=${limit}&offset=${offset}`;
      const data = await getJson(origin, path, opts);
      const results = Array.isArray(data.results) ? data.results : (Array.isArray(data) ? data : []);
      out.push(...results);
      if (!data.paging || !data.paging.nextPage) break;
      offset += limit;
      if (results.length < limit) break;
    }
    return out;
  }

  // Concurrency-limited map. Resolves to results in input order.
  // fn receives (item, index). Rejections propagate as {ok:false} when
  // collectErrors is true, so one course never aborts the export.
  async function limitedMap(items, limit, fn, collectErrors) {
    const results = new Array(items.length);
    let next = 0;
    async function worker() {
      while (next < items.length) {
        const i = next++;
        try {
          results[i] = { ok: true, value: await fn(items[i], i) };
        } catch (e) {
          if (!collectErrors) throw e;
          results[i] = { ok: false, error: e };
        }
      }
    }
    const workers = [];
    for (let w = 0; w < Math.max(1, Math.min(limit, items.length)); w++) workers.push(worker());
    await Promise.all(workers);
    return results;
  }

  // Strip anything credential-like from an error for diagnostics.
  function sanitizeError(e) {
    const msg = String((e && e.message) || e || "unknown error").slice(0, 300);
    return msg
      .replace(/(BbRouter|JSESSIONID|session_id|authenti?cation|authorization|cookie|token|secret|password)[^\s;]*/gi, "$1=[redacted]");
  }

  // Blackboard's calendar API rejects ranges longer than 16 weeks (HTTP 400).
  const MAX_CALENDAR_DAYS = 112;
  function calendarWindows(since, until, maxDays = MAX_CALENDAR_DAYS) {
    const out = [];
    let start = Date.parse(since);
    const end = Date.parse(until);
    if (Number.isNaN(start) || Number.isNaN(end) || end <= start) return out;
    const step = maxDays * 864e5;
    while (start < end) {
      const stop = Math.min(start + step, end);
      out.push({ since: new Date(start).toISOString(), until: new Date(stop).toISOString() });
      start = stop;
    }
    return out;
  }

  // First non-empty value under any of `keys`, breadth-first and depth-bounded.
  // Blackboard nests due dates in handler-specific contentDetail shapes.
  function findKey(obj, keys, maxDepth = 4) {
    let level = [obj];
    for (let depth = 0; depth <= maxDepth && level.length; depth++) {
      const next = [];
      for (const o of level) {
        if (!o || typeof o !== "object") continue;
        for (const k of keys) if (o[k] != null && o[k] !== "") return o[k];
        for (const v of Object.values(o)) if (v && typeof v === "object") next.push(v);
      }
      level = next;
    }
    return null;
  }

  const api = {
    extractRichText, htmlToText, normalizeTimestamp, getJson, pagedGet,
    limitedMap, sanitizeError, isTransientStatus, sleep, calendarWindows, findKey
  };
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  else global.BBUtils = api;
})(typeof self !== "undefined" ? self : (typeof window !== "undefined" ? window : globalThis));

// ---- src/bb-model.js ----
/* BB domain model: assessment classification, current-course detection,
 * ID-stable dedupe/merge, and privacy redaction. Pure functions (no fetch/DOM).
 */
(function (global) {
  "use strict";

  function normKey(...parts) {
    return parts.map((p) => (p == null ? "" : String(p).trim().toLowerCase())).join("|");
  }

  // ---- Assessment classification ----
  // Uses structured signals first (gradebook category, contentHandler, column
  // metadata); title keywords only as a last resort. Never invents certainty:
  // returns "Other" when signals are absent.
  function classifyAssessment({ column, content } = {}) {
    const col = column || {};
    const cont = content || {};
    const handler = (cont.contentHandler && cont.contentHandler.id) || cont.handler || "";
    const category = col.gradebookCategory || col.category || col.gradebookCategoryId || "";
    const catName = (typeof category === "object" ? (category.title || category.name) : category) || "";
    const colName = [col.name, col.displayName].filter(Boolean).join(" ");
    const hay = `${catName} ${colName}`.toLowerCase();

    // Attendance: usually a dedicated category or explicit column.
    if (/attendance/.test(hay)) return "Attendance";
    // Manual grade columns: Blackboard marks these; title fallback last.
    if (col.isManualColumn === true || /manual/.test(String(col.calculationType || "").toLowerCase())) return "Manual";
    // Test/quiz vs exam: prefer category, then handler subtype, then title.
    if (/exam|final|midterm|mid-term/.test(hay)) return "Exam";
    if (/test|quiz/.test(hay)) return "Quiz";
    // Assignment handlers without test semantics.
    if (/assignment/.test(String(handler).toLowerCase())) return "Assignment";
    if (/assess|survey/.test(String(handler).toLowerCase())) {
      // x-bb-asmt-test-link covers both Ultra assignments and tests.
      if (/test|quiz|exam/.test(hay)) return /exam/.test(hay) ? "Exam" : "Quiz";
      if (/assign/.test(hay) || !hay.trim()) return "Assignment";
    }
    if (/assign|homework|project|essay|lab|report|submission/.test(hay)) return "Assignment";
    return "Other";
  }

  // ---- Current-course detection ----
  // Combines structured signals; never relies solely on name formatting.
  // Returns { current: bool, reasons: [] }.
  function isCurrentCourse(course, membership, termsById, nowMs) {
    const now = nowMs || Date.now();
    const reasons = [];
    let score = 0;
    const c = course || {};
    const m = membership || {};

    const avail = (c.availability && c.availability.available) || c.availability;
    if (avail === "Yes" || avail === "Term" || avail === true) {
      score += 1;
      reasons.push("available");
    } else if (avail === "No" || avail === "Disabled" || avail === false) {
      score -= 3;
      reasons.push("unavailable");
    }

    const dur = (c.availability && (c.availability.duration || c.availability.adaptiveRelease)) || c.duration;
    if (dur && (dur.start || dur.end)) {
      const s = dur.start ? Date.parse(dur.start) : NaN;
      const e = dur.end ? Date.parse(dur.end) : NaN;
      if (!Number.isNaN(s) && !Number.isNaN(e)) {
        if (s <= now && now <= e) { score += 3; reasons.push("within course dates"); }
        else { score -= 2; reasons.push("outside course dates"); }
      } else if (!Number.isNaN(e)) {
        if (now <= e) { score += 1; reasons.push("before course end"); }
        else { score -= 2; reasons.push("after course end"); }
      }
    }

    const termId = c.termId || c.term_id;
    const term = termId && termsById ? termsById.get(termId) : null;
    if (term) {
      const s = term.start ? Date.parse(term.start) : NaN;
      const e = term.end ? Date.parse(term.end) : NaN;
      if (!Number.isNaN(s) && !Number.isNaN(e)) {
        if (s <= now && now <= e) { score += 3; reasons.push("current term"); }
        else { score -= 2; reasons.push("non-current term"); }
      }
    }

    // Enrollment recency: active enrollment within ~240 days suggests current.
    const enroll = m.enrollmentDate || m.enrollment || c.enrollmentDate;
    if (enroll) {
      const t = Date.parse(enroll);
      if (!Number.isNaN(t)) {
        const days = (now - t) / 864e5;
        if (days >= 0 && days <= 240) { score += 1; reasons.push("recent enrollment"); }
        else if (days > 540) { score -= 1; reasons.push("old enrollment"); }
      }
    }

    // Course-code year hint: weakest signal, tiebreaker only.
    const code = [c.courseId, c.externalId, c.displayName, c.name].filter(Boolean).join(" ");
    const yearMatch = code.match(/(20\d{2})/);
    if (yearMatch) {
      const y = parseInt(yearMatch[1], 10);
      const nowY = new Date(now).getFullYear();
      if (y === nowY || y === nowY - 0) { score += 1; reasons.push("current year hint"); }
      else if (y < nowY - 1) { score -= 1; reasons.push("old year hint"); }
    }

    return { current: score > 0, score, reasons };
  }

  // ---- Stable assessment identity ----
  // Strong evidence only: shared Blackboard IDs (contentId, columnId, calendar
  // dynamicCalendarItemProps.id, identical source IDs). Titles alone never merge.
  function assessmentMergeKey(a) {
    const ids = [a.column_id, a.content_id, a.calendar_id].filter(Boolean);
    if (ids.length) return `ids:${ids.map((x) => String(x).toLowerCase()).sort().join("+")}`;
    return null;
  }

  function mergeAssessments(list) {
    // Index by every strong ID each record carries.
    const idToGroup = new Map();
    const groups = [];
    function groupFor(record) {
      const ids = [record.column_id, record.content_id, record.calendar_id, record.source_id]
        .filter(Boolean).map((x) => `id:${String(x).toLowerCase()}`);
      let target = null;
      for (const id of ids) {
        if (idToGroup.has(id)) { target = idToGroup.get(id); break; }
      }
      if (!target) {
        target = [];
        groups.push(target);
      }
      for (const id of ids) {
        if (idToGroup.has(id) && idToGroup.get(id) !== target) {
          // Two groups share an ID: union them (transitive closure).
          const other = idToGroup.get(id);
          for (const r of other) { if (!target.includes(r)) target.push(r); }
          const idx = groups.indexOf(other);
          if (idx >= 0) groups.splice(idx, 1);
          for (const [k, v] of idToGroup) if (v === other) idToGroup.set(k, target);
        }
        idToGroup.set(id, target);
      }
      if (!target.includes(record)) target.push(record);
      return target;
    }
    const singletons = [];
    for (const r of list) {
      const hasId = r.column_id || r.content_id || r.calendar_id || r.source_id;
      if (!hasId) singletons.push(r);
      else groupFor(r);
    }
    const out = [];
    for (const g of groups) out.push(mergeGroup(g));
    // Records with no IDs at all are kept as-is (no title-based merging).
    for (const s of singletons) out.push(s);
    return out;
  }

  function mergeGroup(group) {
    if (group.length === 1) return group[0];
    const base = { ...group[0] };
    base.merged_source_ids = group.map((g) => g.source_id).filter(Boolean);
    base.merged_ids = {
      column_ids: [...new Set(group.map((g) => g.column_id).filter(Boolean))],
      content_ids: [...new Set(group.map((g) => g.content_id).filter(Boolean))],
      calendar_ids: [...new Set(group.map((g) => g.calendar_id).filter(Boolean))]
    };
    // Union strong IDs onto the top level so the merged record stays joinable.
    if (!base.column_id && base.merged_ids.column_ids.length) base.column_id = base.merged_ids.column_ids[0];
    if (!base.content_id && base.merged_ids.content_ids.length) base.content_id = base.merged_ids.content_ids[0];
    if (!base.calendar_id && base.merged_ids.calendar_ids.length) base.calendar_id = base.merged_ids.calendar_ids[0];
    for (const g of group.slice(1)) {
      for (const f of ["description", "due_date", "available_from", "available_until",
        "submission_status", "submitted_at", "grade", "possible", "percentage",
        "feedback", "attempt_id", "url", "type"]) {
        if ((base[f] == null || base[f] === "") && g[f] != null && g[f] !== "") base[f] = g[f];
      }
      if (g.description && (base.description || "").length < g.description.length) base.description = g.description;
      // Union attempts/feedback lists when present.
      if (Array.isArray(g.attempts) && g.attempts.length) {
        base.attempts = [...(base.attempts || []), ...g.attempts];
      }
    }
    if (Array.isArray(base.attempts)) {
      const seen = new Set();
      base.attempts = base.attempts.filter((a) => {
        const k = (a && (a.id || a.attempt_id)) || JSON.stringify(a);
        if (seen.has(k)) return false;
        seen.add(k);
        return true;
      });
    }
    return base;
  }

  // ---- Redaction ----
  // Removes/pseudonymizes user identifiers; preserves course/content/assessment IDs.
  function redactExport(data) {
    const clone = JSON.parse(JSON.stringify(data));
    const userMap = new Map();
    function token(prefix) {
      const n = userMap.size + 1;
      return `${prefix}_REDACTED_${n}`;
    }
    function redactUserId(v) {
      if (v == null) return v;
      const k = String(v);
      if (!userMap.has(k)) userMap.set(k, token("USER"));
      return userMap.get(k);
    }
    if (clone.user) {
      if (clone.user.id) clone.user.id = redactUserId(clone.user.id);
      if (clone.user.userName) clone.user.userName = "REDACTED";
      if (clone.user.email) clone.user.email = "REDACTED";
      if (clone.user.studentId) clone.user.studentId = "REDACTED";
      if (clone.user.externalId) clone.user.externalId = "REDACTED";
    }
    if (clone.diagnostics) {
      delete clone.diagnostics.userId;
      delete clone.diagnostics.userName;
    }
    const userish = ["userId", "user_id", "author_id", "createdById", "membership_id", "membershipId", "enrollment_id"];
    function walk(o) {
      if (Array.isArray(o)) { o.forEach(walk); return; }
      if (o && typeof o === "object") {
        for (const k of Object.keys(o)) {
          if (userish.includes(k) && typeof o[k] === "string") o[k] = redactUserId(o[k]);
          else if ((k === "email" || k === "studentId" || k === "userName") && typeof o[k] === "string") o[k] = "REDACTED";
          else if (k === "instructors" && Array.isArray(o[k])) {
            o[k] = o[k].map((ins) => ({ ...(ins || {}), email: ins && ins.email ? "REDACTED" : ins && ins.email, userId: ins && ins.userId ? redactUserId(ins.userId) : ins && ins.userId }));
          } else if (k === "author" && typeof o[k] === "string") {
            o[k] = redactUserId(o[k]);
          } else walk(o[k]);
        }
      }
    }
    walk(clone.courses);
    walk(clone.assessments);
    walk(clone.announcements);
    walk(clone.grades);
    walk(clone.content);
    walk(clone.materials);
    walk(clone.events);
    walk(clone.assignments);
    if (clone.diagnostics) walk(clone.diagnostics.samples);
    return clone;
  }

  // Submitted/graded work is never "overdue"; attendance columns are not deadlines.
  const DONE_STATUS = /^(graded|needsgrading|needs_grading|submitted|completed|inprogress|in_progress)$/i;
  function deadlineFlags(a, nowMs) {
    const due = a && a.due_date ? Date.parse(a.due_date) : NaN;
    if (Number.isNaN(due) || (a && a.type === "Attendance")) return { is_upcoming: false, is_overdue: false };
    const done = DONE_STATUS.test(String(a.submission_status || "")) ||
      (Array.isArray(a.attempts) && a.attempts.length > 0) || (a.grade != null && a.grade !== "");
    return { is_upcoming: !done && due >= nowMs, is_overdue: !done && due < nowMs };
  }

  // Instructor records from either the public memberships list or Ultra's
  // course `instructorsMembership` expansion. Students are filtered out.
  function instructorsFrom(payload) {
    if (!payload || typeof payload !== "object") return [];
    const rows = Array.isArray(payload.instructorsMembership) ? payload.instructorsMembership
      : Array.isArray(payload.results) ? payload.results
      : Array.isArray(payload) ? payload : [];
    const fromUltra = Array.isArray(payload.instructorsMembership);
    const out = [];
    for (const r of rows) {
      if (!r || typeof r !== "object") continue;
      const role = String(r.courseRoleId || r.role || (r.courseRole && r.courseRole.roleId) || "");
      if (!fromUltra && !/instructor|faculty|teacher|\bta\b/i.test(role)) continue;
      const u = r.user || r;
      const nm = u.name || {};
      const name = [nm.given || u.givenName, nm.family || u.familyName].filter(Boolean).join(" ") || u.userName || null;
      const email = (u.contact && u.contact.email) || u.emailAddress || u.email || null;
      if (name || email) out.push({ name, email, userId: r.userId || u.id || null });
    }
    return out;
  }

  // Running standing from the student's own grades (graded items only count).
  function gradeSummary(grades, assessments) {
    let earned = 0, possible = 0, graded = 0, pending = 0;
    for (const g of grades || []) {
      if (typeof g.score === "number" && typeof g.possible === "number" && g.possible > 0) {
        earned += g.score; possible += g.possible; graded++;
      } else if (/needs_?grading/i.test(String(g.status || ""))) pending++;
    }
    const missing = (assessments || []).filter((a) => a.is_overdue).length;
    const round = (n) => Math.round(n * 10) / 10;
    return { earned: round(earned), possible: round(possible), percentage: possible ? round((earned / possible) * 100) : null, graded, pending, missing };
  }

  const api = { normKey, classifyAssessment, isCurrentCourse, assessmentMergeKey, mergeAssessments, redactExport, deadlineFlags, instructorsFrom, gradeSummary };
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  else global.BBModel = api;
})(typeof self !== "undefined" ? self : (typeof window !== "undefined" ? window : globalThis));

// ---- src/ics.js ----
/* IAU Blackboard ICS parser — no dependencies, works in browser + Node.
 * Parses RFC 5545 VEVENT blocks needed for Blackboard calendar feeds.
 * Read-only, no network calls here. Fetching is done by the caller.
 */
(function (global) {
  "use strict";

  function unfoldLines(text) {
    // RFC 5545 line unfolding: lines starting with space/tab continue previous line
    const raw = text.replace(/\r\n/g, "\n").replace(/\r/g, "\n").split("\n");
    const out = [];
    for (const line of raw) {
      if (line.startsWith(" ") || line.startsWith("\t")) {
        if (out.length) out[out.length - 1] += line.slice(1);
      } else {
        out.push(line);
      }
    }
    return out;
  }

  function unescapeText(s) {
    return s.replace(/\\n/gi, "\n").replace(/\\,/g, ",").replace(/\\;/g, ";").replace(/\\\\/g, "\\");
  }

  function parseDateTime(value, params) {
    if (!value) return null;
    // DATE: YYYYMMDD -> treat as UTC midnight
    if (/^\d{8}$/.test(value)) {
      const y = value.slice(0, 4), m = value.slice(4, 6), d = value.slice(6, 8);
      return `${y}-${m}-${d}T00:00:00.000Z`;
    }
    // DATE-TIME: YYYYMMDDTHHMMSS[Z] or with TZID param
    const m = value.match(/^(\d{4})(\d{2})(\d{2})T(\d{2})(\d{2})(\d{2})(Z)?$/);
    if (m) {
      const [, y, mo, d, h, mi, s, z] = m;
      if (z) return `${y}-${mo}-${d}T${h}:${mi}:${s}.000Z`;
      // No Z: Blackboard exports in UTC with Z in practice. If TZID present,
      // we keep the wall time and mark Z only if params say UTC; otherwise
      // return as-is with Z assumption documented by caller.
      // To avoid inventing a timezone, return naive wall time + note.
      if (params && /UTC/i.test(params)) return `${y}-${mo}-${d}T${h}:${mi}:${s}.000Z`;
      return `${y}-${mo}-${d}T${h}:${mi}:${s}.000Z`;
    }
    return null;
  }

  function splitProp(line) {
    // "DTSTART;VALUE=DATE:20240101" -> {name, params, value}
    const colon = line.indexOf(":");
    if (colon < 0) return null;
    const left = line.slice(0, colon);
    const value = line.slice(colon + 1);
    const semi = left.indexOf(";");
    if (semi < 0) return { name: left.toUpperCase(), params: "", value };
    return { name: left.slice(0, semi).toUpperCase(), params: left.slice(semi + 1), value };
  }

  function parseICS(text) {
    const lines = unfoldLines(text);
    const events = [];
    let cur = null;
    for (const line of lines) {
      const upper = line.toUpperCase();
      if (upper === "BEGIN:VEVENT") { cur = {}; continue; }
      if (upper === "END:VEVENT") {
        if (cur) events.push(cur);
        cur = null;
        continue;
      }
      if (!cur) continue;
      const p = splitProp(line);
      if (!p) continue;
      const v = p.value;
      switch (p.name) {
        case "UID": cur.uid = v; break;
        case "SUMMARY": cur.summary = unescapeText(v); break;
        case "DESCRIPTION": cur.description = unescapeText(v); break;
        case "LOCATION": cur.location = unescapeText(v); break;
        case "URL": cur.url = v; break;
        case "DTSTART": cur.start = parseDateTime(v, p.params); cur._dtstartRaw = v; break;
        case "DTEND": cur.end = parseDateTime(v, p.params); break;
        case "DUE": cur.due = parseDateTime(v, p.params); break;
        case "DTSTAMP": cur.dtstamp = parseDateTime(v, p.params); break;
        case "CATEGORIES": cur.categories = unescapeText(v); break;
        case "STATUS": cur.status = v; break;
        default:
          // Keep X- props that Blackboard sometimes uses for course info
          if (p.name.startsWith("X-")) {
            cur.x = cur.x || {};
            cur.x[p.name] = unescapeText(v);
          }
          break;
      }
    }
    return events;
  }

  // Blackboard ICS SUMMARY is often "CourseName: AssignmentName" or similar.
  // Split heuristically but always keep full summary.
  function toExtractorEvents(icsEvents, origin) {
    return icsEvents.map((e) => {
      const due = e.due || e.start || null;
      let course = null;
      let title = e.summary || "(no title)";
      // Heuristic split on first ": " or " - " if it looks like "CODE ... : Title"
      const m = (e.summary || "").match(/^(.{3,}?):\s+(.{3,})$/);
      if (m) { course = m[1].trim(); title = m[2].trim(); }
      return {
        title,
        course,
        start: e.start || null,
        end: e.end || null,
        due_date: due,
        description: e.description || null,
        location: e.location || null,
        url: e.url || null,
        source_id: e.uid ? `ics:${e.uid}` : null,
        source: "ics",
        _raw_summary: e.summary || null
      };
    });
  }

  const api = { parseICS, toExtractorEvents, unfoldLines };
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  else { global.BB_ICS = api; }
})(typeof self !== "undefined" ? self : (typeof window !== "undefined" ? window : globalThis));

// ---- src/extractor.js ----
/* IAU Blackboard read-only extractor core (v2).
 * Builds on the proven authenticated-session pipeline; does not replace it with
 * DOM scraping. GET requests only. No password/MFA handling. Uses the browser's
 * existing login cookies via same-origin fetch.
 *
 * Endpoint policy (no brute-force enumeration):
 *  - Identity/courses/memberships/contents/announcements/columns: the endpoints
 *    this extractor has historically used successfully (kept as-is).
 *  - Grades: documented student-readable paths only —
 *      GET /learn/api/public/v1/courses/{courseId}/gradebook/users/{userId}
 *      GET /learn/api/public/v1|courses/{courseId}/gradebook/columns/{columnId}/users/{userId}
 *    The previously attempted `/users/{uid}/grades` path 404s and is NOT retried.
 *  - Calendar: existing structured calendar sweep (kept) + ICS fallback (kept).
 *
 * Usage (console, on https://vle.iau.edu.sa/ultra...):
 *   const data = await BBExtractor.extractAll({ origin: location.origin, scope: "current" });
 *
 * Options: { origin, scope: "current"|"all" (default "current"),
 *   redact: false, concurrency: 3, timeoutMs: 20000, retries: 2,
 *   since, until, icsEvents: [], onProgress(msg) }
 */
(function (global) {
  "use strict";

  const DEFAULT_ORIGIN = "https://vle.iau.edu.sa";
  // Known-bad path: returns 404 for students. Documented here so nobody re-adds it.
  const KNOWN_BAD_GRADE_PATHS = [
    "/learn/api/public/v2/courses/{courseId}/users/{userId}/grades"
  ];

  function loadDeps() {
    let U = global.BBUtils;
    let M = global.BBModel;
    if ((!U || !M) && typeof require !== "undefined") {
      try { U = U || require("./bb-utils.js"); } catch { /* browser */ }
      try { M = M || require("./bb-model.js"); } catch { /* browser */ }
    }
    if (!U) throw new Error("BBUtils not loaded (src/bb-utils.js must load before extractor.js)");
    if (!M) throw new Error("BBModel not loaded (src/bb-model.js must load before extractor.js)");
    return { U, M };
  }

  function nowISO() { return new Date().toISOString(); }

  function courseUrl(origin, courseInternalId) {
    return `${origin}/ultra/courses/${courseInternalId}/outline`;
  }
  function contentUrl(origin, courseInternalId, contentId) {
    return `${origin}/ultra/courses/${courseInternalId}/outline?contentId=${encodeURIComponent(contentId)}`;
  }

  function dedupeByKey(records, keyFn) {
    const seen = new Set();
    const out = [];
    for (const r of records) {
      const k = keyFn(r);
      if (!k) { out.push(r); continue; }
      if (seen.has(k)) continue;
      seen.add(k);
      out.push(r);
    }
    return out;
  }

  function handlerOf(item) {
    const h = item && item.contentHandler;
    return (typeof h === "string" ? h : (h && h.id)) || (item && item.handler) || "";
  }

  // Map raw contentHandler IDs (documented by Anthology) to friendly types.
  function contentTypeOf(item) {
    const h = handlerOf(item);
    switch (h) {
      case "resource/x-bb-folder": return "Folder";
      case "resource/x-bb-file": return "File";
      case "resource/x-bb-document": return "Document";
      case "resource/x-bb-externallink": return "Link";
      case "resource/x-bb-courselink": return "CourseLink";
      case "resource/x-bb-forumlink": return "DiscussionLink";
      case "resource/x-bb-blti-link": return "LTI";
      case "resource/x-bb-asmt-test-link": return "Assessment";
      case "resource/x-bb-assignment": return "Assignment";
      default: return h ? h.replace("resource/x-bb-", "x-bb-") : "Other";
    }
  }

  function percentageOf(score, possible) {
    if (typeof score !== "number" || typeof possible !== "number" || !possible) return null;
    return Math.round((score / possible) * 1000) / 10;
  }

  async function extractAll(options = {}) {
    const { U, M } = loadDeps();
    const origin = (options.origin || (typeof location !== "undefined" ? location.origin : DEFAULT_ORIGIN)).replace(/\/$/, "");
    const scope = options.scope === "all" ? "all" : "current";
    const wantRedact = !!options.redact;
    const concurrency = Math.max(1, Math.min(options.concurrency || 3, 5));
    const timeoutMs = options.timeoutMs || 20000;
    const retries = options.retries != null ? options.retries : 2;
    const since = options.since || new Date(Date.now() - 120 * 864e5).toISOString();
    const until = options.until || new Date(Date.now() + 180 * 864e5).toISOString();
    const windows = U.calendarWindows(since, until);
    const onProgress = typeof options.onProgress === "function" ? options.onProgress : null;
    const prog = (m) => { try { if (onProgress) onProgress(m); } catch { /* ignore */ } };
    const samples = options.captureSamples ? {} : null;
    const USER_KEYS = /^(email|emailAddress|userName|studentId|contact|name|givenName|familyName|displayName|nickName|middleName|externalId|uuid|userId|createdBy|creator)$/;
    const EMAIL_RE = /[^\s@]+@[^\s@]+\.[^\s@]+/;
    function sample(family, raw) {
      if (!samples || samples[family] || !raw || typeof raw !== "object") return;
      samples[family] = JSON.parse(JSON.stringify(raw, (k, v) => (USER_KEYS.test(k) ? undefined : (typeof v === "string" ? (EMAIL_RE.test(v) ? "REDACTED" : v.slice(0, 120)) : v))));
    }

    const startedAt = Date.now();
    const sources = [];
    function recordSource(source, endpoint, status, count, ms, error) {
      sources.push({
        source, endpoint, status,
        count: count == null ? 0 : count,
        elapsed_ms: Math.round(ms),
        ...(error ? { error: U.sanitizeError(error) } : {})
      });
    }
    async function track(source, endpoint, fn) {
      const t0 = Date.now();
      try {
        const value = await fn();
        const count = Array.isArray(value) ? value.length : (value && value.count != null ? value.count : 1);
        recordSource(source, endpoint, "ok", count, Date.now() - t0);
        return value;
      } catch (e) {
        const status = e && e.status === 403 ? "forbidden" : (e && e.status ? `http_${e.status}` : "failed");
        recordSource(source, endpoint, status, 0, Date.now() - t0, e);
        throw e;
      }
    }

    const diagnostics = { origin, startedAt: nowISO(), scope, endpointStatus: {} };
    const courses = [];
    const assessments = [];
    const announcements = [];
    const grades = [];
    const events = [];
    const content = [];

    // ---- 1. identity (proven endpoint, kept) ----
    let me = null;
    try {
      me = await track("identity", "GET /learn/api/v1/users/me",
        () => U.getJson(origin, "/learn/api/v1/users/me", { timeoutMs, retries }));
      diagnostics.endpointStatus["/learn/api/v1/users/me"] = "ok";
    } catch (e) {
      diagnostics.endpointStatus["/learn/api/v1/users/me"] = `failed: ${U.sanitizeError(e)}`;
      throw new Error(`Not logged into Blackboard at ${origin} (${U.sanitizeError(e)}). Open ${origin}/ultra and log in first.`);
    }
    const myUserId = me.id;

    // ---- 2. memberships -> courses (proven endpoint, kept) ----
    let memberships = [];
    try {
      memberships = await track("memberships", "GET /learn/api/v1/users/me/memberships",
        () => U.pagedGet(origin, "/learn/api/v1/users/me/memberships?expand=course", { limit: 100, maxPages: 10, timeoutMs, retries }));
      diagnostics.endpointStatus["/learn/api/v1/users/me/memberships"] = "ok";
    } catch (e) {
      diagnostics.endpointStatus["/learn/api/v1/users/me/memberships"] = `failed: ${U.sanitizeError(e)}`;
    }
    sample("memberships", memberships[0]);
    const membershipByCourse = new Map();
    for (const m of memberships) {
      const cid = (m.course && m.course.id) || m.courseId;
      if (cid && !membershipByCourse.has(cid)) membershipByCourse.set(cid, m);
    }

    // ---- 2b. terms (for current-course detection; best-effort) ----
    let termsById = new Map();
    try {
      const terms = await track("terms", "GET /learn/api/v1/terms",
        () => U.pagedGet(origin, "/learn/api/v1/terms", { limit: 100, maxPages: 5, timeoutMs, retries }));
      for (const t of terms) {
        if (t && t.id) termsById.set(t.id, { name: t.name || null, start: t.availability && t.availability.duration && t.availability.duration.start, end: t.availability && t.availability.duration && t.availability.duration.end });
      }
    } catch (e) {
      recordSource("terms", "GET /learn/api/v1/terms", "skipped", 0, 0, e);
    }

    const courseById = new Map();
    for (const m of memberships) {
      const c = m.course || {};
      const cid = c.id || m.courseId;
      if (!cid || courseById.has(cid)) continue;
      const current = M.isCurrentCourse(c, m, termsById);
      const entry = {
        id: cid,
        course_id: cid,
        courseId: c.courseId || c.externalId || null,
        code: c.courseId || c.externalId || null,
        name: c.displayName || c.name || "(unnamed course)",
        availability: (c.availability && c.availability.available) ?? null,
        availability_duration: (c.availability && (c.availability.duration || null)) || null,
        enrollment_date: m.enrollmentDate || null,
        enrollment: m.enrollmentDate || null,
        role: m.courseRoleId || m.role || null,
        term_id: c.termId || c.term_id || null,
        term_name: (termsById.get(c.termId || c.term_id) || {}).name || null,
        final_grade: null,
        created: U.normalizeTimestamp(c.created),
        modified: U.normalizeTimestamp(c.modified),
        is_current: current.current,
        current_score: current.score,
        current_reasons: current.reasons,
        url: courseUrl(origin, cid),
        _membership_id: m.id || null
      };
      courseById.set(cid, entry);
      courses.push(entry);
    }

    // Fallback if memberships empty (proven fallback, kept).
    if (courses.length === 0) {
      try {
        const data = await track("courses-fallback", "GET /learn/api/public/v1/users/{id}/courses",
          () => U.pagedGet(origin, `/learn/api/public/v1/users/${encodeURIComponent(myUserId)}/courses`, { limit: 100, maxPages: 5, timeoutMs, retries }));
        for (const c of data) {
          const cid = c.courseId || c.id;
          if (!cid || courseById.has(cid)) continue;
          const e = { id: cid, course_id: cid, courseId: c.courseId || null, code: c.courseId || null, name: c.displayName || c.name || cid, availability: null, enrollment_date: null, role: null, term_id: null, term_name: null, final_grade: null, created: null, modified: null, is_current: true, current_reasons: ["fallback-listing"], url: courseUrl(origin, cid) };
          courseById.set(cid, e);
          courses.push(e);
        }
      } catch (e) {
        diagnostics.endpointStatus["/learn/api/public/v1/users/{id}/courses"] = `failed: ${U.sanitizeError(e)}`;
      }
    }

    const inScope = scope === "all" ? courses : courses.filter((c) => c.is_current);
    const scopedNote = scope === "all" ? null : (courses.length && inScope.length === 0 ? "current-filter-empty" : null);
    prog(`Courses: ${inScope.length} in scope / ${courses.length} total`);

    // ---- 3. per-course reads (isolated; conservative concurrency) ----
    const results = await U.limitedMap(inScope, concurrency, async (course) => {
      const cid = course.id;
      const cname = course.name;
      const per = { assessments: [], announcements: [], grades: [], events: [], content: [] };

      // 3a. instructors: students get 404 on the roster, so probe student-readable
      // shapes in order and stop at the first that yields instructors.
      const instructorProbes = [
        ["ultra-course", `/learn/api/v1/courses/${encodeURIComponent(cid)}?expand=instructorsMembership`],
        ["public-memberships", `/learn/api/public/v1/courses/${encodeURIComponent(cid)}/users?role=Instructor&expand=user`]
      ];
      course.instructor_source = null;
      for (const [label, path] of instructorProbes) {
        const t0 = Date.now();
        try {
          const payload = await U.getJson(origin, path, { timeoutMs, retries: 1 });
          sample(`instructors-${label}`, payload);
          const found = M.instructorsFrom(payload);
          recordSource(`instructors:${cid}`, `GET ${label}`, found.length ? "ok" : "probe_empty", found.length, Date.now() - t0);
          if (found.length) { course.instructors = found; course.instructor_source = label; break; }
        } catch (e) {
          recordSource(`instructors:${cid}`, `GET ${label}`, `probe_${e && e.status ? `http_${e.status}` : "failed"}`, 0, Date.now() - t0, e);
        }
      }

      // 3b. contents: documented public API first (stable shape: contentHandler.id,
      // hasChildren, created/modified); Ultra's internal list is the fallback.
      const contentIndex = new Map(); // contentId -> record
      const contentBases = [
        `/learn/api/public/v1/courses/${encodeURIComponent(cid)}/contents`,
        `/learn/api/v1/courses/${encodeURIComponent(cid)}/contents`
      ];
      let tops = null;
      let base = null;
      for (const b of contentBases) {
        try {
          tops = await track(`contents:${cid}`, `GET ${b.includes("/public/") ? "public" : "ultra"} contents`,
            () => U.pagedGet(origin, b, { limit: 100, maxPages: 5, timeoutMs, retries }));
          base = b;
          break;
        } catch { /* recorded; try the next shape */ }
      }
      sample("contents", tops && tops[0]);
      const attachmentJobs = [];
      if (tops) {
        const queue = tops.map((t) => ({ item: t, parentId: null, path: [t.title || "(untitled)"] }));
        const seen = new Set();
        while (queue.length) {
          const { item, parentId, path } = queue.shift();
          if (!item || !item.id || seen.has(item.id)) continue;
          seen.add(item.id);
          const handler = handlerOf(item);
          const type = contentTypeOf(item);
          const bodyR = U.extractRichText(item.body);
          const bodyText = U.htmlToText(bodyR.text);
          const embedded = bodyText && /^https?:\/\/\S+\/embedded\/?$/.test(bodyText) ? bodyText : null;
          const created = item.created || item.createdDate;
          const modified = item.modified || item.modifiedDate;
          const rec = {
            course: cname, course_id: cid,
            title: item.title || "(untitled)",
            content_id: item.id,
            source_id: item.id,
            type,
            handler: handler || null,
            parent_id: parentId,
            path: path.join(" / "),
            description: embedded ? null : bodyText,
            body_text: embedded ? null : bodyText,
            body_html: bodyR.html || (typeof item.body === "string" && !embedded ? item.body : null),
            embedded_url: embedded,
            availability: (item.availability && item.availability.available) ?? null,
            available_from: U.normalizeTimestamp(item.availability && item.availability.adaptiveRelease && item.availability.adaptiveRelease.start),
            available_until: U.normalizeTimestamp(item.availability && item.availability.adaptiveRelease && item.availability.adaptiveRelease.end),
            created: U.normalizeTimestamp(created),
            modified: U.normalizeTimestamp(modified),
            dates: {
              due: U.normalizeTimestamp((item.dates && item.dates.due) || U.findKey(item.contentDetail || {}, ["dueDate", "due"])),
              start: U.normalizeTimestamp(item.dates && item.dates.start),
              end: U.normalizeTimestamp(item.dates && item.dates.end)
            },
            url: contentUrl(origin, cid, item.id),
            attachments: [],
            external_link: (item.contentHandler && item.contentHandler.url) || item.externalLink || null
          };
          contentIndex.set(item.id, rec);
          per.content.push(rec);
          if (/x-bb-(file|document|assignment)/.test(handler)) attachmentJobs.push(rec);
          const isFolder = item.hasChildren || /x-bb-(folder|lesson)/.test(handler);
          if (isFolder) {
            try {
              const kids = await U.pagedGet(origin, `${base}/${encodeURIComponent(item.id)}/children`, { limit: 100, maxPages: 5, timeoutMs, retries });
              for (const k of kids) queue.push({ item: k, parentId: item.id, path: [...path, k.title || "(untitled)"] });
            } catch { /* keep what we have */ }
          }
        }
      }

      // 3b'. attachment metadata (documented); bytes are never fetched here.
      const attT0 = Date.now();
      let attListingErrors = 0;
      await U.limitedMap(attachmentJobs.slice(0, 80), 2, async (rec) => {
        const listPath = `/learn/api/public/v1/courses/${encodeURIComponent(cid)}/contents/${encodeURIComponent(rec.content_id)}/attachments`;
        try {
          const res = await U.getJson(origin, listPath, { timeoutMs, retries: 1 });
          sample("attachments", (res.results || [])[0]);
          rec.attachments = (res.results || []).filter((a) => a && a.id).map((a) => ({
            id: a.id || null,
            name: a.fileName || a.name || null,
            mime: a.mimeType || null,
            size: a.fileSize ?? a.size ?? null,
            download_url: `${origin}${listPath}/${encodeURIComponent(a.id)}/download`
          }));
        } catch (e) {
          if (!(e && e.status === 404)) attListingErrors++; // 404 = no attachments, normal
        }
      }, true);
      if (attachmentJobs.length) {
        const attCount = attachmentJobs.reduce((n, r) => n + r.attachments.length, 0);
        recordSource(`attachments:${cid}`, "GET public attachments", attListingErrors ? "partial" : "ok", attCount, Date.now() - attT0);
        Object.assign(sources[sources.length - 1], { truncated: attachmentJobs.length > 80, listing_errors: attListingErrors });
      }

      // 3c. announcements (proven endpoint, kept) — fixed rich-text extraction.
      try {
        const anns = await track(`announcements:${cid}`, "GET /learn/api/v1/courses/{id}/announcements",
          () => U.pagedGet(origin, `/learn/api/v1/courses/${encodeURIComponent(cid)}/announcements`, { limit: 100, maxPages: 5, timeoutMs, retries }));
        sample("announcements", anns[0]);
        for (const a of anns) {
          const r = U.extractRichText(a.body);
          const authorRaw = a.createdBy || a.creator || null;
          const author = typeof authorRaw === "string" ? authorRaw
            : authorRaw ? (authorRaw.userName || authorRaw.id || null) : null;
          per.announcements.push({
            course: cname, course_id: cid,
            title: (typeof a.title === "string" ? a.title : U.extractRichText(a.title).text) || "(announcement)",
            body_text: U.htmlToText(r.text),
            body_html: r.html || (r.text && /<[a-z]/i.test(r.text) ? r.text : null),
            body: U.htmlToText(r.text),
            created_at: U.normalizeTimestamp(a.created),
            updated_at: U.normalizeTimestamp(a.modified),
            posted_on: U.normalizeTimestamp(a.created || a.modified),
            author,
            announcement_id: a.id || null,
            source_id: a.id || null,
            url: courseUrl(origin, cid)
          });
        }
      } catch { /* recorded */ }

      // 3d. gradebook columns (proven endpoint, kept) — metadata for assessments.
      let columns = [];
      try {
        columns = await track(`columns:${cid}`, "GET /learn/api/public/v2/courses/{id}/gradebook/columns",
          () => U.pagedGet(origin, `/learn/api/public/v2/courses/${encodeURIComponent(cid)}/gradebook/columns`, { limit: 100, maxPages: 5, timeoutMs, retries }));
      } catch { columns = []; }
      sample("columns", columns[0]);
      // The course total ("externalGrade") is a final grade, not an assessment.
      const totalColumn = columns.find((c) => c.externalGrade === true) || null;
      columns = columns.filter((c) => c !== totalColumn);
      const columnById = new Map([...columns, ...(totalColumn ? [totalColumn] : [])].map((c) => [c.id, c]));
      const contentByColumnContentId = new Map();
      for (const rec of contentIndex.values()) {
        // columns reference content via contentId; index not strictly needed
        // since we join on IDs below, kept for clarity.
        void rec;
      }

      // Category titles (columns only carry category IDs) for classification.
      const categoryById = new Map();
      try {
        const cats = await U.pagedGet(origin, `/learn/api/public/v1/courses/${encodeURIComponent(cid)}/gradebook/categories`, { limit: 100, maxPages: 2, timeoutMs, retries: 1 });
        for (const c of cats) if (c && c.id) categoryById.set(c.id, c.title || c.name || null);
      } catch { /* optional */ }
      for (const col of columns) {
        if (!col.gradebookCategory && categoryById.get(col.gradebookCategoryId)) col.gradebookCategory = { title: categoryById.get(col.gradebookCategoryId) };
      }
      for (const col of columns) {
        const grading = col.grading || {};
        const descR = U.extractRichText(col.description);
        per.assessments.push({
          course: cname, course_id: cid,
          title: col.name || col.displayName || "(graded item)",
          description: U.htmlToText(descR.text),
          due_date: U.normalizeTimestamp(grading.due || col.due || U.findKey(col, ["dueDate"])),
          available_from: U.normalizeTimestamp(grading.availableFrom || (col.availability && col.availability.start)),
          available_until: U.normalizeTimestamp(grading.availableUntil || (col.availability && col.availability.end)),
          submission_status: null, submitted_at: null,
          grade: null, possible: (col.score && col.score.possible) ?? null,
          percentage: null, feedback: null, attempts: [],
          type: M.classifyAssessment({ column: col, content: col.contentId && contentIndex.get(col.contentId) }),
          content_id: col.contentId || null,
          column_id: col.id,
          calendar_id: null, attempt_id: null,
          gradebook_category: (col.gradebookCategory && (col.gradebookCategory.title || col.gradebookCategory.name)) || col.gradebookCategoryId || null,
          url: contentUrl(origin, cid, col.contentId || col.id),
          source_id: col.id,
          source: "gradebook-column"
        });
      }

      // Content-side assessment candidates (proven heuristic, kept) with IDs.
      for (const rec of contentIndex.values()) {
        const h = rec.handler || "";
        if (/assess|assign|test|survey|grade/i.test(h)) {
          per.assessments.push({
            course: cname, course_id: cid,
            title: rec.title,
            description: rec.description,
            due_date: (rec.dates && rec.dates.due) || null,
            available_from: rec.available_from || (rec.dates && rec.dates.start) || null,
            available_until: rec.available_until || (rec.dates && rec.dates.end) || null,
            submission_status: null, submitted_at: null,
            grade: null, possible: null, percentage: null, feedback: null, attempts: [],
            type: M.classifyAssessment({ column: { name: rec.title }, content: { contentHandler: { id: h } } }),
            content_id: rec.content_id,
            column_id: null, calendar_id: null, attempt_id: null,
            url: rec.url, source_id: rec.content_id,
            source: "content"
          });
        }
      }

      // 3e. grades — documented student-readable paths ONLY.
      // Primary: GET /learn/api/public/v1/courses/{courseId}/gradebook/users/{userId}
      // Fallback: per-column GET .../columns/{columnId}/users/{userId} (bounded).
      // The `/users/{uid}/grades` path (no /gradebook/) 404s and is never called.
      const gradeByColumn = new Map();
      let userGrades = [];
      try {
        const g = await track(`usergrades:${cid}`, "GET /learn/api/public/v1/courses/{id}/gradebook/users/{userId}",
          () => U.getJson(origin, `/learn/api/public/v1/courses/${encodeURIComponent(cid)}/gradebook/users/${encodeURIComponent(myUserId)}?limit=100`, { timeoutMs, retries }));
        userGrades = g.results || g.grades || (g.columnId ? [g] : []);
      } catch {
        // Bounded per-column fallback (documented path).
        const todo = [...(totalColumn ? [totalColumn] : []), ...columns.slice(0, 10)]; // total first so the cap cannot drop the final grade
        const res = await U.limitedMap(todo, 2, async (col) => {
          const t0 = Date.now();
          try {
            const one = await U.getJson(origin, `/learn/api/public/v1/courses/${encodeURIComponent(cid)}/gradebook/columns/${encodeURIComponent(col.id)}/users/${encodeURIComponent(myUserId)}`, { timeoutMs, retries: 1 });
            recordSource(`grade:${cid}:${col.id}`, "GET .../columns/{columnId}/users/{userId}", "ok", 1, Date.now() - t0);
            return one;
          } catch (e) {
            // 403 = hidden from students (normal); 404 = no grade yet. Quiet.
            recordSource(`grade:${cid}:${col.id}`, "GET .../columns/{columnId}/users/{userId}", e && e.status ? `http_${e.status}` : "failed", 0, Date.now() - t0, e);
            return null;
          }
        }, true);
        for (const r of res) {
          if (r.ok && r.value && (r.value.columnId || r.value.status)) userGrades.push(r.value);
        }
      }
      sample("grades", userGrades[0]);
      for (const gr of userGrades) {
        if (!gr || typeof gr !== "object") continue;
        if (totalColumn && gr.columnId === totalColumn.id) {
          const score = typeof gr.score === "number" ? gr.score : (gr.displayGrade && gr.displayGrade.score) ?? null;
          const possible = (gr.displayGrade && gr.displayGrade.possible) ?? (totalColumn.score && totalColumn.score.possible) ?? null;
          course.final_grade = { score, possible, percentage: percentageOf(score, possible), text: (gr.displayGrade && gr.displayGrade.text) ?? null };
          continue;
        }
        const col = columnById.get(gr.columnId) || {};
        const score = typeof gr.score === "number" ? gr.score : (gr.displayGrade && gr.displayGrade.score) ?? null;
        const possible = (gr.displayGrade && gr.displayGrade.possible) ?? col.score?.possible ?? null;
        const fb = U.extractRichText(gr.feedback);
        per.grades.push({
          course: cname, course_id: cid,
          item: col.name || col.displayName || gr.columnId || "(grade)",
          column_id: gr.columnId || null,
          score, possible,
          percentage: percentageOf(score, possible),
          grade: (gr.displayGrade && gr.displayGrade.text) ?? gr.text ?? null,
          status: gr.status || null,
          submission_status: gr.status || null,
          feedback: U.htmlToText(fb.text),
          feedback_html: fb.html || (typeof gr.feedback === "string" ? gr.feedback : null),
          posted: U.normalizeTimestamp(gr.modified || gr.created),
          attempts: [],
          url: contentUrl(origin, cid, col.contentId || gr.columnId || cid),
          source_id: gr.columnId ? `grade:${cid}:${gr.columnId}` : null
        });
        if (gr.columnId) gradeByColumn.set(gr.columnId, gr);
      }

      // 3f. attempts (bounded): submission status + submitted timestamp.
      const assessed = per.assessments.filter((a) => a.column_id).slice(0, 10);
      await U.limitedMap(assessed, 2, async (a) => {
        try {
          const att = await U.getJson(origin, `/learn/api/public/v2/courses/${encodeURIComponent(cid)}/gradebook/columns/${encodeURIComponent(a.column_id)}/users/${encodeURIComponent(myUserId)}/attempts?limit=5`, { timeoutMs, retries: 1 });
          const list = att.results || att.attempts || [];
          if (list.length) {
            const last = list[list.length - 1];
            a.attempts = list.map((x) => ({
              id: x.id || null,
              status: x.status || null,
              created: U.normalizeTimestamp(x.created),
              modified: U.normalizeTimestamp(x.modified),
              submitted_at: U.normalizeTimestamp(x.modified || x.created),
              feedback: U.extractRichText(x.feedback).text
            }));
            a.submission_status = last.status || "Submitted";
            a.submitted_at = U.normalizeTimestamp(last.modified || last.created);
            a.attempt_id = last.id || null;
          }
        } catch { /* not attempt-based; skip quietly */ }
      }, true);

      // Back-fill assessment grade fields from grades.
      for (const a of per.assessments) {
        if (!a.column_id) continue;
        const gr = gradeByColumn.get(a.column_id);
        if (gr) {
          a.submission_status = a.submission_status || gr.status || null;
          const score = typeof gr.score === "number" ? gr.score : (gr.displayGrade && gr.displayGrade.score) ?? null;
          const possible = (gr.displayGrade && gr.displayGrade.possible) ?? a.possible ?? null;
          a.possible = possible;
          a.grade = (gr.displayGrade && gr.displayGrade.text) ?? gr.text ?? a.grade;
          a.percentage = percentageOf(score, possible);
          a.feedback = a.feedback || U.extractRichText(gr.feedback).text;
        }
      }

      // 3g. structured calendar sweep per course, in <= 16-week windows (longer -> HTTP 400).
      for (const w of windows) {
        try {
          const cal = await track(`calendar:${cid}`, "GET /learn/api/public/v1/calendars/items",
            () => U.getJson(origin, `/learn/api/public/v1/calendars/items?courseId=${encodeURIComponent(cid)}&since=${encodeURIComponent(w.since)}&until=${encodeURIComponent(w.until)}`, { timeoutMs, retries }));
          sample("calendar", (cal.results || [])[0]);
          for (const it of (cal.results || [])) {
            const dynId = it.dynamicCalendarItemProps && it.dynamicCalendarItemProps.id;
            per.events.push({
              title: it.title || "(event)",
              course: cname, course_id: cid,
              description: U.extractRichText(it.description).text,
              start: U.normalizeTimestamp(it.start),
              end: U.normalizeTimestamp(it.end),
              due_date: U.normalizeTimestamp(it.end || it.start),
              type: it.type || null,
              calendar_id: it.id || null,
              uid: it.id || null,
              url: (it.dynamicCalendarItemProps && it.dynamicCalendarItemProps.link) || courseUrl(origin, cid),
              source_id: it.id ? `cal:${it.id}` : null,
              source: "api-calendar"
            });
            if (it.type === "GradebookColumn" && dynId) {
              const ax = per.assessments.find((x) => x.column_id === dynId);
              if (ax) {
                ax.calendar_id = it.id || ax.calendar_id;
                if (!ax.due_date) ax.due_date = U.normalizeTimestamp(it.end || it.start);
              }
            }
          }
        } catch { /* recorded */ }
      }

      return per;
    }, true);

    for (const r of results) {
      if (!r.ok) continue; // per-course isolation: failure recorded by track(); export continues
      assessments.push(...r.value.assessments);
      announcements.push(...r.value.announcements);
      grades.push(...r.value.grades);
      events.push(...r.value.events);
      content.push(...r.value.content);
    }

    // ---- 4. global calendar sweep (kept) ----
    for (const w of windows) {
      try {
        const g = await track("calendar-global", "GET /learn/api/public/v1/calendars/items",
          () => U.getJson(origin, `/learn/api/public/v1/calendars/items?since=${encodeURIComponent(w.since)}&until=${encodeURIComponent(w.until)}`, { timeoutMs, retries }));
        for (const it of (g.results || [])) {
          const cid = it.calendarId || it.courseId || null;
          const cname = it.calendarName || (cid && courseById.get(cid)?.name) || null;
          events.push({
            title: it.title || "(event)", course: cname, course_id: cid,
            description: U.extractRichText(it.description).text,
            start: U.normalizeTimestamp(it.start),
            end: U.normalizeTimestamp(it.end),
            due_date: U.normalizeTimestamp(it.end || it.start),
            type: it.type || null, calendar_id: it.id || null, uid: it.id || null,
            url: cid ? courseUrl(origin, cid) : null,
            source_id: it.id ? `cal:${it.id}` : null,
            source: "api-calendar"
          });
        }
      } catch { /* recorded */ }
    }

    // ---- 5. ICS merge (kept as fallback/supplement) ----
    if (Array.isArray(options.icsEvents)) {
      for (const e of options.icsEvents) {
        events.push({
          title: e.title || e._raw_summary || "(event)",
          course: e.course || null, course_id: null,
          description: e.description || null,
          start: U.normalizeTimestamp(e.start),
          end: U.normalizeTimestamp(e.end),
          due_date: U.normalizeTimestamp(e.due_date || e.start),
          type: "ics", calendar_id: null,
          uid: e.source_id ? String(e.source_id).replace(/^ics:/, "") : (e.uid || null),
          url: e.url || null, source_id: e.source_id || null, source: "ics"
        });
      }
    }

    // ---- 6. ID-stable dedupe/merge (titles alone NEVER merge) ----
    const assessmentsM = M.mergeAssessments(assessments);
    const nowMs = Date.now();
    for (const a of assessmentsM) Object.assign(a, M.deadlineFlags(a, nowMs));
    const announcementsD = dedupeByKey(announcements, (a) => a.source_id || a.announcement_id || null);
    const gradesD = dedupeByKey(grades, (g) => g.source_id || (g.column_id ? `grade:${g.course_id}:${g.column_id}` : null));
    const eventsD = dedupeByKey(events, (e) => e.source_id || (e.uid ? `uid:${e.uid}` : null));
    const contentD = dedupeByKey(content, (m) => m.source_id || m.content_id || null);
    for (const c of courses) {
      c.grade_summary = M.gradeSummary(gradesD.filter((g) => g.course_id === c.id), assessmentsM.filter((a) => a.course_id === c.id));
    }

    // Backward-compatible aliases for the previous schema.
    const assignmentsAlias = assessmentsM.map((a) => ({
      course: a.course, course_id: a.course_id, title: a.title,
      description: a.description, due_date: a.due_date,
      submission_status: a.submission_status, grade: a.grade,
      possible: a.possible, url: a.url, source_id: a.source_id,
      content_id: a.content_id, column_id: a.column_id, attempt_id: a.attempt_id,
      type: a.type,
      is_upcoming: a.is_upcoming, is_overdue: a.is_overdue
    }));
    const materialsAlias = contentD;

    // Probe misses and 403s on closed courses are expected, not failures.
    const failedSources = sources.filter((s) => s.status !== "ok" && s.status !== "skipped" && s.status !== "forbidden" && !String(s.status).startsWith("probe_"));
    const summary = {
      courses_total: courses.length,
      courses_current: courses.filter((c) => c.is_current).length,
      courses_in_scope: inScope.length,
      scope,
      assessments: assessmentsM.length,
      announcements: announcementsD.length,
      grades: gradesD.length,
      events: eventsD.length,
      content: contentD.length,
      upcoming_deadlines: assessmentsM.filter((a) => a.is_upcoming).length,
      overdue: assessmentsM.filter((a) => a.is_overdue).length,
      failed_sources: failedSources.length,
      elapsed_ms: Date.now() - startedAt,
      ...(scopedNote ? { note: scopedNote } : {})
    };

    let out = {
      exported_at: nowISO(),
      source: "IAU Blackboard",
      origin,
      user: me ? { id: me.id, userName: me.userName || null } : null,
      courses: scope === "all" ? courses : inScope,
      assessments: assessmentsM.filter((a) => scope === "all" || (courseById.get(a.course_id)?.is_current ?? true)),
      assignments: assignmentsAlias.filter((a) => scope === "all" || (courseById.get(a.course_id)?.is_current ?? true)),
      announcements: announcementsD.filter((a) => scope === "all" || (courseById.get(a.course_id)?.is_current ?? true)),
      grades: gradesD.filter((g) => scope === "all" || (courseById.get(g.course_id)?.is_current ?? true)),
      events: eventsD,
      content: contentD.filter((m) => scope === "all" || (courseById.get(m.course_id)?.is_current ?? true)),
      materials: materialsAlias.filter((m) => scope === "all" || (courseById.get(m.course_id)?.is_current ?? true)),
      diagnostics: {
        ...diagnostics,
        ...(samples ? { samples } : {}),
        sources,
        failed_sources: failedSources.map((s) => `${s.source}: ${s.status}${s.error ? ` (${s.error})` : ""}`),
        summary,
        known_bad_paths_skipped: KNOWN_BAD_GRADE_PATHS
      },
      summary
    };

    if (wantRedact) out = M.redactExport(out);
    return out;
  }

  const api = { extractAll, DEFAULT_ORIGIN, KNOWN_BAD_GRADE_PATHS };
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  else global.BBExtractor = api;
})(typeof self !== "undefined" ? self : (typeof window !== "undefined" ? window : globalThis));

const opts = Object.assign({ scope: "current", redact: false }, window.BB_EXTRACT_OPTIONS || {});
const data = await BBExtractor.extractAll({ ...opts, origin: location.origin, onProgress: (m) => console.log("[BB]", m) });
const s = data.summary;
console.log("[BB] Courses: " + s.courses_current + " current / " + s.courses_total + " total · Assessments: " + s.assessments + " · Upcoming: " + s.upcoming_deadlines + " · Overdue: " + s.overdue + " · Announcements: " + s.announcements + " · Grades: " + s.grades + " · Events: " + s.events + " · Content: " + s.content + " · Failed sources: " + s.failed_sources);
const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
const a = document.createElement("a");
a.href = URL.createObjectURL(blob);
a.download = "iau-blackboard-export-" + new Date().toISOString().slice(0, 10) + ".json";
a.click();
setTimeout(() => URL.revokeObjectURL(a.href), 5000);
return data;
})();
