const $=id=>document.getElementById(id);
const icons={
profile:'<circle cx="32" cy="21" r="11"/><path d="M10 57c0-25 44-25 44 0M48 28l7 7 12-14"/>',
roadmap:'<path d="M32 6v9c0 14-19 10-19 23s32 5 32 18v8"/><circle cx="32" cy="6" r="4"/><circle cx="13" cy="38" r="5"/><circle cx="45" cy="62" r="4"/><path d="M45 24h15M45 19l5 5-5 5"/>',
coach:'<rect x="8" y="15" width="49" height="36" rx="13"/><path d="M20 51l-3 10 16-10M32 15V6M25 6h14"/><circle cx="23" cy="33" r="2"/><circle cx="43" cy="33" r="2"/><path d="M25 41q8 6 16 0"/>',
project:'<rect x="6" y="13" width="52" height="36" rx="4"/><path d="M1 57h63M23 25l-7 6 7 6M42 25l7 6-7 6M36 22l-8 19"/>',
team:'<circle cx="32" cy="19" r="8"/><circle cx="12" cy="29" r="7"/><circle cx="53" cy="29" r="7"/><path d="M21 52v-9c0-14 22-14 22 0v9M3 59V47c0-11 17-11 17 0M45 59V47c0-11 17-11 17 0"/>',
career:'<rect x="7" y="23" width="51" height="33" rx="7"/><path d="M23 23v-9h18v9M7 35q25 18 51 0M29 40h8v8h-8z"/>',
context:'<circle cx="32" cy="32" r="9"/><circle cx="32" cy="5" r="4"/><circle cx="59" cy="32" r="4"/><circle cx="32" cy="59" r="4"/><circle cx="5" cy="32" r="4"/><path d="M32 9v14M41 32h14M32 41v14M9 32h14"/>',
trust:'<path d="M32 5l23 9v20c0 15-23 27-23 27S9 49 9 34V14zM20 32l8 9 17-19"/>'};
const icon=k=>`<svg viewBox="0 0 66 66" aria-hidden="true">${icons[k]}</svg>`;
const features=[
{key:'profile',title:'أنت تؤكّد كل معلومة',short:'ملفك الشخصي',tag:'بداية مبنية عليك',paper:'#f1eaff',accent:'#8053c6',sub:'من سيرتك ومشاريعك… إلى ملف يعرفك فعلاً.',image:9,points:[['يجمع خلفيتك','السجل الأكاديمي، السيرة الذاتية، GitHub ومشاريعك.'],['يعرض الأدلة للمراجعة','البيانات المستوردة اقتراحات حتى تؤكّدها أنت.'],['يبدأ من واقعك','تخصصك واهتماماتك ووقتك تحدد نقطة البداية.']],note:'نبدأ بالتعرف على الطالب. نقرأ السجل والسيرة وGitHub، لكن الاستيراد ليس حقيقة تلقائياً. الطالب يراجع الأدلة ويختار ما يوافق عليه. من هنا نعرف ما تعلمه وما بناه وما يريد الوصول إليه. لقطة المنتج مأخوذة من العرض المرجعي.'},
{key:'roadmap',title:'خريطة طريق مبنية عليك',short:'خريطة الطريق',tag:'خطوتك التالية واضحة',paper:'#def6ef',accent:'#0b8b76',sub:'مقرراتك + أهدافك + وقتك + اللي يطلبه السوق.',image:10,points:[['تعرف وش تتعلم بعدها','مسار يربط أساسيات الجامعة بالتطبيق والمهارات العملية.'],['تتغيّر مع تقدمك','Hermes يقترح فروعاً وتعديلات تناسب اتجاهك الجديد.'],['أنت تقبل التغيير','العمل المكتمل والجاري محفوظ، والتعديلات تحتاج موافقتك.']],note:'الخريطة هي قلب Waypoint. تبني مساراً من المواد والاهتمامات والوقت المتاح، وتضيف مهارات سوق العمل والمشاريع. إذا تغيّر هدف الطالب يقترح Hermes تعديلاً. لا يطبق الاقتراح قبل القبول، ولا يغير العمل المكتمل أو الجاري. الخريطة تجعل القرار التالي واضحاً بدلاً من قائمة دورات بلا ترتيب.'},
{key:'coach',title:'مدرّب يعرف وين وصلت',short:'Hermes المدرّب',tag:'فهم، ممارسة، ثم تقدم',paper:'#ffe9db',accent:'#be6845',sub:'يشرح من اللي تعرفه… ويتأكد إنك فهمت.',image:11,points:[['يعرف سياقك','يستخدم خريطتك ومشاريعك والمعلومات التي أكّدتها.'],['يحوّل الشرح إلى ممارسة','أسئلة وتمارين وبطاقات مراجعة داخل المحادثة.'],['يبني قدرتك','مدرّب يدعم التعلم ويقترح الخطوات، والطالب يقرر.']],note:'مشكلة الدردشة العامة أنها لا تعرف أين وصل الطالب. Hermes يستخدم سياق الخريطة والأدلة المؤكدة، فيشرح بناء على ما تعرفه. وفي المحادثة يمكن أن تظهر أسئلة وتمارين وبطاقات مراجعة. الهدف ليس تسليم إجابة فقط؛ الهدف أن تبني فهماً وتعرف كيف تكمل بنفسك.'},
{key:'project',title:'تتعلم… وتبني شيء توريه',short:'المشاريع والتقييم',tag:'من معرفة إلى دليل',paper:'#e4efff',accent:'#416fbe',sub:'كل مرحلة تقود إلى تطبيق عملي يمكن تقييمه.',image:12,points:[['مشاريع مرتبطة بمسارك','تطبق المعرفة في شيء يخدم هدفك واهتماماتك.'],['تقييم بالأدلة','تشغيل وفحوص في بيئة معزولة للمشاريع المدعومة.'],['تقدم تقدر تثبته','المشروع والعمل الفعلي يصبحان دليلاً على مهاراتك.']],note:'نربط التعلم بالبناء. يختار الطالب مشروعاً مناسباً لمرحلته، ثم يمكن تقييم الملفات المدعومة داخل بيئة معزولة بفحوص وأدلة. التقييم ليس ادعاء دعم كل أنواع المشاريع. نريد أن يستطيع الطالب إظهار ما أنجزه، لا أن يقول فقط إنه شاهد دورة.'},
{key:'team',title:'Hermes يقترح… الفريق يقرر',short:'المشاريع الجماعية',tag:'كل واحد يتعلم ويساهم',paper:'#fff2cd',accent:'#9f7817',sub:'تعاون أوضح، توزيع أعدل، وقرارات ظاهرة للجميع.',image:17,points:[['من ملف المشروع إلى خطة','استخراج المخرجات والمواعيد ثم مراجعتها قبل اعتمادها.'],['مهام تناسب كل عضو','اقتراح توزيع يراعي المهارات والضغط وفرص التعلم.'],['الفريق يعتمد الاقتراح','المساعد يشرح ويلخّص ويقترح؛ تطبيق التغييرات قرار بشري.']],note:'في المشاريع الجماعية قد يعمل طالب واحد بينما البقية لا يتعلمون. Waypoint يربط توزيع العمل بقدرات الأعضاء وأهدافهم. يراجع الفريق المعلومات المستخرجة من ملف المشروع، ثم يساعد Hermes في المهام والشرح والمتابعة. الاقتراح يمر بقرار عضو أو فريق وفق نوعه، مع سياسة تصويت وصلاحيات قائد موثقة.'},
{key:'career',title:'فرصة تناسبك… قبل آخر لحظة',short:'المسار المهني',tag:'استعداد يبدأ بدري',paper:'#ffe8ed',accent:'#b85478',sub:'من مهاراتك ومشاريعك إلى التدريب التعاوني والسيرة الذاتية.',image:13,points:[['فرص لها سبب','توصيات تشرح علاقتها بمهاراتك واهتماماتك.'],['تعرف الفجوة قبل التقديم','مهارات ناقصة تتحول إلى خطوات مقترحة في خريطتك.'],['تعرض إنجازك بوضوح','بناء سيرة ذاتية من بياناتك المؤكدة ومراجعة مسودتها.']],note:'الاستعداد المهني يبدأ قبل موعد التدريب. نطابق المهارات والمشاريع مع الفرص ونشرح سبب الملاءمة والفجوات. يمكن أن تتحول الفجوات إلى اقتراحات للخريطة. وهناك منشئ سيرة ذاتية من البيانات المؤكدة. هذه توصيات واستعداد، وليست ضمان توظيف أو قبول.'},
{key:'context',title:'كل شيء… في سياق واحد',short:'السياق المتصل',tag:'ما تبدأ من الصفر كل مرة',paper:'#e2f6fa',accent:'#288395',sub:'معلوماتك الجامعية ومشاريعك وفرصك تخدم نفس الرحلة.',points:[['المحتوى الجامعي حاضر','سياق Blackboard يدعم الخريطة والشرح والمتابعة.'],['البريد بموافقتك','قراءة وتصنيف الرسائل المتزامنة مع تحكمك في الوصول.'],['فرص مرتبطة بمسارك','مشاريع وهاكاثونات وتدريب حول أهدافك، لا قوائم منفصلة.']],note:'بدلاً من إعادة شرح نفسك لسبعة تطبيقات، يجمع Waypoint سياق التعلم والمشاريع والفرص. Blackboard والبريد لهما حدود وصول واضحة؛ قراءة البريد اختيارية ولا تتحول الرسائل إلى حقائق عن الطالب. بعض مصادر الفرص تعتمد على فهرسة أو بيانات عرض، فلا ندعي تكاملاً رسمياً شاملاً مع كل مصدر.'},
{key:'trust',title:'بياناتك وقرارك… بيدك',short:'الثقة والتحكم',tag:'اقتراح ذكي، قرار بشري',paper:'#eee9ff',accent:'#7253b7',sub:'المساعد يقترح، والطالب يؤكد ويعتمد.',points:[['الحقيقة في التطبيق','SQLite يحتفظ بالحالة المعتمدة؛ ذاكرة الوكيل سياق مساعد.'],['الأدلة تحتاج مراجعتك','الملفات المستوردة لا تتحول إلى حقائق دون اختيارك.'],['وصول محدود وواضح','مفاتيح الخدمات في الخادم والأدوات مرتبطة بصلاحيات التشغيل.']],note:'الثقة جزء من تصميم المنتج. حالة الطالب والخريطة في SQLite، والوكيل لا يعتمد الحقائق أو يفعّل تعديلات الخريطة بنفسه. المعلومات المستوردة تخضع للمراجعة، ومفاتيح الخدمات تبقى في الخادم. النسخة الحالية تحتاج هوية دخول إنتاجية قبل إطلاق عام. هذه حدود تنفيذ واضحة، وليست وعداً مطلقاً بالأمان.'}
];
const problems=[
{title:'السنة الثالثة…<br>وما زلت ضايع.',desc:'مواد كثيرة. خيارات أكثر.<br>بس وش الخطوة الجاية؟',question:'وين رايح بعد التخرّج؟',color:'#8c66d9',symbol:'<path d="M110 255h90q40 0 40-55v-70M240 200q0 55 60 55h105M240 255v115" stroke="#d8cef0" stroke-width="22" fill="none" stroke-linecap="round"/><circle cx="240" cy="255" r="73" fill="white" stroke="#ad8fe6" stroke-width="5"/><path d="M218 280l12-59 50 12-12 51z" fill="#ba9be8"/><path d="M233 221l-15 59 50 4z" fill="#7050ba"/><text x="210" y="110" font-size="68" fill="#ad8fe6">?</text><circle cx="120" cy="255" r="11" fill="#ad8fe6"/><circle cx="406" cy="255" r="11" fill="#e3c1af"/>'},
{title:'الجامعة شيء.<br>والسوق شيء ثاني.',desc:'تعرف المفهوم نظرياً.<br>بس كيف تبني به شيئاً حقيقياً؟',question:'والتدريب؟ ندور عليه آخر لحظة.',color:'#12a28f',symbol:'<path d="M95 358h320" stroke="#b5e8db" stroke-width="6"/><path d="M130 358v-66h65v-66h65v-66h65v-65" fill="none" stroke="#21ab96" stroke-width="13" stroke-linejoin="round"/><rect x="107" y="190" width="63" height="83" rx="10" fill="#ddf7ed" transform="rotate(-13 107 190)"/><path d="M355 175l-43 18 13-45 55-59z" fill="#f7c774"/><path d="M335 169l20 20" stroke="white" stroke-width="7"/><circle cx="366" cy="111" r="7" fill="white"/><path d="M308 215l-16 24M323 223l-8 22" stroke="#f7c774" stroke-width="6" stroke-linecap="round"/>'},
{title:'الشغل ينسلّم.<br>والتعلّم؟',desc:'جواب جاهز من AI.<br>بس هل فهمت؟ هل تقدر تكمل وحدك؟',question:'حلّ لي الـ lab بسرعة.',color:'#de8a63',symbol:'<rect x="95" y="130" width="235" height="140" rx="33" fill="#fff0e6" stroke="#dfaa89" stroke-width="4"/><path d="M150 268l-15 37 65-37" fill="#fff0e6" stroke="#dfaa89" stroke-width="4"/><path d="M143 180h138M143 216h93" stroke="#d3926a" stroke-width="8" stroke-linecap="round"/><circle cx="343" cy="308" r="69" fill="white" stroke="#ead1bc" stroke-width="4"/><text x="321" y="330" font-size="70" fill="#c9845d">?</text>'},
{title:'سبع تطبيقات.<br>ولا واحد يعرفك.',desc:'ملفات، بريد، محادثات ومواعيد.<br>وكل مرة… تبدأ من الصفر.',question:'وين راحت الصورة الكاملة؟',color:'#5196bd',symbol:'<circle class="small-orbit" cx="260" cy="250" r="145" fill="none" stroke="#cce0ef" stroke-width="3" stroke-dasharray="5 13"/><rect x="85" y="115" width="105" height="76" rx="18" fill="#ddeeff" transform="rotate(-10 85 115)"/><rect x="323" y="136" width="105" height="76" rx="18" fill="#e9e0ff" transform="rotate(10 323 136)"/><rect x="300" y="320" width="105" height="76" rx="18" fill="#fff1cf" transform="rotate(-8 300 320)"/><rect x="78" y="298" width="105" height="76" rx="18" fill="#e0f4ec" transform="rotate(8 78 298)"/><circle cx="260" cy="250" r="49" fill="white" stroke="#87b6d2" stroke-width="4"/><path d="M240 246h40M260 226v40" stroke="#87b6d2" stroke-width="5" stroke-linecap="round"/>'}
];
const centers=[1320,2120,2920,3720];
$('difficulties').innerHTML=problems.map((p,i)=>`<section class="difficulty ${i%2?'right':'left'}" style="top:${centers[i]-210}px"><h2>${p.title}</h2><p>${p.desc}</p><span class="question">${p.question}</span></section><div class="problem-symbol ${i%2?'left':''}" style="top:${centers[i]-240}px"><svg viewBox="0 0 520 520" aria-hidden="true">${p.symbol}</svg></div>`).join('');
const positions=features.map((f,i)=>({x:165+(i%4)*325,y:4980+Math.floor(i/4)*360}));
$('cards').innerHTML=features.map((f,i)=>`<button class="route-card" id="card-${i}" style="left:${positions[i].x}px;top:${positions[i].y}px;--paper:${f.paper};--accent:${f.accent}" aria-label="افتح قسم ${f.short}"><span class="card-number">${String(i+1).padStart(2,'0')}</span><span class="card-icon">${icon(f.key)}</span><h2>${f.short}</h2><p>${f.tag}</p></button>`).join('');
document.querySelector('.arrival').style.top='4770px';
const roadD='M800 465 C800 720 740 850 800 1150 S860 1600 800 1950 S740 2400 800 2750 S860 3200 800 3550 S740 4140 800 4620 L800 4850 C800 4960 815 4900 815 5060 L815 5750';
for(const id of ['road','road-shadow','road-trace'])$(id).setAttribute('d',roadD);
$('branches').innerHTML=positions.map((p,i)=>`<path d="M815 ${p.y+128} C${p.x+145} ${p.y+128} ${p.x+145} ${p.y-35} ${p.x+145} ${p.y}" stroke="${features[i].accent}" stroke-opacity=".35" stroke-width="3" fill="none" stroke-linecap="round"/>`).join('');
let state=0,busy=false,viewScale=1,camera={x:800,y:450,s:1},notesOpen=false;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const times=[15,18,18,18,18,13,23,32,28,23,23,23,15,23,10];
const notes=['نبدأ بالشعار: Waypoint رفيق الطالب من أول يوم في الجامعة حتى التخرج. الرحلة تبدأ بسؤال بسيط: كيف أعرف ما الخطوة الجاية؟','أحياناً نصل السنة الثالثة وما زلنا لا نعرف كيف ترتبط المواد بمستقبلنا. المشكلة ليست قلة الخيارات، بل غياب ترتيب واضح لها.','الجامعة تعطي الأساس العلمي، لكن الانتقال إلى بناء منتج والتعاون في فريق يحتاج ممارسة وأدوات حديثة واستعداداً مهنياً مبكراً.','الإجابات الجاهزة تختصر وقت التسليم، لكنها لا تضمن الفهم. نحتاج مساعداً يشرح ويسأل ويجعل الطالب قادراً على العمل بنفسه.','كل أداة تعرف جزءاً صغيراً: المواد هنا، الملفات هناك، والفرص في مكان آخر. كل مرة نعيد شرح خلفيتنا من البداية.','هنا تبدأ فكرة Waypoint: نجمع الرحلة في سياق واحد. هذه الخريطة تعرض أقسام المنتج، وسنفتح كل قسم لنرى دوره في مسار الطالب.',...features.map(f=>f.note),'نعود إلى الفكرة الأولى: لو بدأ الطالب مع Waypoint من أول يوم، تصبح الخطوة التالية أوضح. هذه الخريطة هي ما نريد أن يتوفر لكل طالب. شكراً، ونرحب بأسئلتكم.'];
function resize(){viewScale=Math.min(innerWidth/1600,innerHeight/900);$('stage').style.transform=`scale(${viewScale})`;$('stage').style.left=`${(innerWidth-1600*viewScale)/2}px`;$('stage').style.top=`${(innerHeight-900*viewScale)/2}px`}
const routeLength=$('road').getTotalLength();
function roadPoint(y){let lo=0,hi=routeLength;for(let i=0;i<16;i++){const m=(lo+hi)/2;if($('road').getPointAtLength(m).y<y)lo=m;else hi=m}return $('road').getPointAtLength((lo+hi)/2)}
function placeTraveler(y){const p=roadPoint(y);$('traveler').style.top=p.y+'px';$('traveler').style.left=p.x+'px'}
function apply(){ $('world').style.transform=`translate3d(${800-camera.x*camera.s}px,${450-camera.y*camera.s}px,0) scale(${camera.s})` }
function wait(ms){return new Promise(r=>setTimeout(r,reduced?0:ms))}
function tweenCamera(target,ms=1500,follow=false){const from={...camera},travelerFrom=parseFloat($('traveler').style.top)||715;if(reduced){camera={...target};apply();return Promise.resolve()};return new Promise(resolve=>{const start=performance.now();function frame(now){let p=Math.min((now-start)/ms,1),e=p<.5?4*p*p*p:1-Math.pow(-2*p+2,3)/2;camera.y=from.y+(target.y-from.y)*e;camera.s=from.s+(target.s-from.s)*e;camera.x=from.x+(target.x-from.x)*e;if(follow){const r=roadPoint(camera.y);camera.x=r.x+(from.x-roadPoint(from.y).x)*(1-e);placeTraveler(travelerFrom+(target.y-travelerFrom)*e)}apply();if(p<1)requestAnimationFrame(frame);else resolve()}requestAnimationFrame(frame)})}
function panelRect(i){const r=$(`card-${i}`).getBoundingClientRect(),base=$('stage').getBoundingClientRect();return{x:(r.left-base.left)/viewScale,y:(r.top-base.top)/viewScale,w:r.width/viewScale,h:r.height/viewScale}}
function screenVisual(f){return `<div class="screen"><img src="assets/image${f.image}.png" alt="لقطة من واجهة ${f.short} في العرض المرجعي" draggable="false"></div><p class="visual-caption">من واجهة Waypoint</p>`}
function customVisual(f){if(f.key==='context')return `<div class="connection-pills"><span>Blackboard</span><span>Outlook</span><span>GitHub</span><span>CV</span><span>Hackathons</span><span>Co-op</span></div><div class="connection-thread"></div><div class="connection-core">Waypoint</div><div class="connection-thread"></div><p class="visual-caption">السياق يتصل. والقرار يبقى لك.</p>`;return `<div class="trust-visual"><div class="trust-orbit"></div><svg viewBox="0 0 66 66" aria-hidden="true">${icons.trust}</svg><span class="trust-label">أنت تؤكّد · أنت تعتمد</span></div>`}
function populate(i){const f=features[i],panel=$('feature');panel.style.setProperty('--paper',f.paper);panel.style.setProperty('--accent',f.accent);$('feature-count').textContent=`${String(i+1).padStart(2,'0')} / 08`;$('feature-foot').textContent=f.short;$('feature-content').classList.remove('revealed');$('feature-content').style.opacity=0;$('feature-content').innerHTML=`<h1 class="section-title">${f.title}</h1><p class="section-subtitle">${f.sub}</p><div class="feature-columns"><div class="feature-copy">${f.points.map(([a,b])=>`<div class="point"><h3>${a}</h3><p>${b}</p></div>`).join('')}</div><div class="feature-visual">${f.image?screenVisual(f):customVisual(f)}</div></div>`}
async function expand(i){const p=panelRect(i);populate(i);const panel=$('feature');panel.hidden=false;panel.style.transform=`translate(${p.x}px,${p.y}px) scale(${p.w/1600},${p.h/900})`;const anim=panel.animate([{transform:panel.style.transform,borderRadius:'100px'},{transform:'translate(0,0) scale(1)',borderRadius:'0px'}],{duration:reduced?0:850,easing:'cubic-bezier(.22,1,.36,1)',fill:'forwards'});await anim.finished;panel.style.transform='none';anim.cancel();$('feature-content').style.opacity=1;$('feature-content').classList.add('revealed');$(`card-${i}`).classList.add('visited');await wait(220)}
async function collapse(i){$('feature-content').classList.remove('revealed');const fade=$('feature-content').animate([{opacity:1},{opacity:0}],{duration:reduced?0:180,fill:'forwards'});await fade.finished;const p=panelRect(i),panel=$('feature'),anim=panel.animate([{transform:'none',borderRadius:'0px'},{transform:`translate(${p.x}px,${p.y}px) scale(${p.w/1600},${p.h/900})`,borderRadius:'100px'}],{duration:reduced?0:650,easing:'cubic-bezier(.65,0,.35,1)',fill:'forwards'});await anim.finished;panel.hidden=true;anim.cancel();fade.cancel();panel.style.transform='none';$('feature-content').style.opacity=0}
function update(){let label=state===0?'البداية':state<=4?'تحديات الطالب':state===5?'خريطة Waypoint':state===14?'الخطوة الجاية':features[state-6].short;$('status').textContent=label;$('progress-fill').style.width=`${state/14*100}%`;$('prev').disabled=state===0;$('next').disabled=state===14;$('announcer').textContent=label;$('note-text').textContent=notes[state];$('note-time').textContent=`الوقت المقترح: ${times[state]} ثانية · إجمالي العرض ٥ دقائق`;$('hint').style.opacity=state>0?'0':'1';document.body.dataset.state=state}
async function go(next){if(busy||next===state||next<0||next>14)return;busy=true;document.body.dataset.busy='true';try{const previous=state;if(previous>=6&&previous<=13)await collapse(previous-6);if(previous===14){$('ending').hidden=true}if(previous>=6&&previous<=13)await tweenCamera({x:800,y:5200,s:1},800);state=next;update();if(next<=5){const y=next===0?450:next===5?5200:centers[next-1];await tweenCamera({x:800,y,s:1},next===5?2100:1600,true);placeTraveler(next===0?715:y)}else if(next<=13){const i=next-6,p=positions[i];if(previous<5)await tweenCamera({x:800,y:5200,s:1},1800,true);await tweenCamera({x:p.x+145,y:p.y+128,s:1.5},900);await expand(i)}else{await tweenCamera({x:800,y:5280,s:.83},1200);$('ending').hidden=false;const anim=$('ending').animate([{opacity:0},{opacity:1}],{duration:reduced?0:900,fill:'forwards'});await anim.finished;anim.cancel()}}finally{busy=false;document.body.dataset.busy='false'}}
function forward(){go(state+1)}function backward(){go(state-1)}
$('next').onclick=forward;$('prev').onclick=backward;$('overview').onclick=()=>go(5);$('notes-button').onclick=()=>{notesOpen=!notesOpen;$('notes').hidden=!notesOpen;$('notes-button').setAttribute('aria-pressed',notesOpen)};
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{}}
features.forEach((f,i)=>$(`card-${i}`).onclick=()=>go(i+6));
document.addEventListener('keydown',e=>{if(e.ctrlKey||e.metaKey||e.altKey)return;if(e.target.closest('button')&&[' ','Enter'].includes(e.key))return;if(['ArrowRight','ArrowDown','PageDown',' ','Enter'].includes(e.key)){e.preventDefault();forward()}else if(['ArrowLeft','ArrowUp','PageUp'].includes(e.key)){e.preventDefault();backward()}else if(e.key.toLowerCase()==='o'){e.preventDefault();go(5)}else if(e.key.toLowerCase()==='n'){$('notes-button').click()}else if(e.key.toLowerCase()==='f'){$('fullscreen').click()}else if(e.key==='Home'){e.preventDefault();go(0)}else if(e.key==='Escape'&&notesOpen){$('notes-button').click()}});
$('viewport').addEventListener('click',e=>{if(e.target.closest('button')||e.target.closest('#notes'))return;forward()});
let startTouch;document.addEventListener('touchstart',e=>{startTouch=e.touches[0].clientX},{passive:true});document.addEventListener('touchend',e=>{if(startTouch==null)return;const d=e.changedTouches[0].clientX-startTouch;if(Math.abs(d)>60){d<0?forward():backward()}startTouch=null},{passive:true});
window.addEventListener('resize',resize);resize();apply();update();
window.waypointPresentation={go,get state(){return state},get busy(){return busy},features,times};

