"""team openings and join requests

Revision ID: 7d3923fe0194
Revises: 0003_classes
"""
from alembic import op
import sqlalchemy as sa


revision = '0004_openings'
down_revision = '0003_classes'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_join_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'account_id', name='uq_join_request_team_account')
    )
    op.create_index(op.f('ix_team_join_requests_account_id'), 'team_join_requests', ['account_id'], unique=False)
    op.create_index(op.f('ix_team_join_requests_team_id'), 'team_join_requests', ['team_id'], unique=False)
    op.create_table('team_openings',
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('roles_json', sa.Text(), nullable=False),
    sa.Column('commitment', sa.String(length=160), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('team_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_openings')
    op.drop_index(op.f('ix_team_join_requests_team_id'), table_name='team_join_requests')
    op.drop_index(op.f('ix_team_join_requests_account_id'), table_name='team_join_requests')
    op.drop_table('team_join_requests')
    # ### end Alembic commands ###
