"""peer classes and invitation codes

Revision ID: 952c46212c3b
Revises: 0002_teams
"""
from alembic import op
import sqlalchemy as sa


revision = '0003_classes'
down_revision = '0002_teams'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_rates',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('window', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('code_invites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=True),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.Column('revoked', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_hash')
    )
    op.create_table('invite_redemptions',
    sa.Column('invite_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['invite_id'], ['code_invites.id'], ),
    sa.PrimaryKeyConstraint('invite_id', 'account_id')
    )
    op.add_column('courses', sa.Column('organizer_id', sa.String(length=36), nullable=True))
    op.add_column('courses', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()))
    op.alter_column('courses', 'created_at', server_default=None)
    op.create_foreign_key('fk_course_organizer', 'courses', 'accounts', ['organizer_id'], ['id'])
    op.create_table('class_removals',
        sa.Column('course_id', sa.String(36), sa.ForeignKey('courses.id'), primary_key=True),
        sa.Column('account_id', sa.String(36), sa.ForeignKey('accounts.id'), primary_key=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('class_removals')
    op.drop_constraint('fk_course_organizer', 'courses', type_='foreignkey')
    op.drop_column('courses', 'created_at')
    op.drop_column('courses', 'organizer_id')
    op.drop_table('invite_redemptions')
    op.drop_table('code_invites')
    op.drop_table('invite_rates')
    # ### end Alembic commands ###
