"""reviewed shared profiles and preferences

Revision ID: 95c1eff5090f
Revises: 0005_lifecycle
"""
from alembic import op
import sqlalchemy as sa


revision = '0006_profiles'
down_revision = '0005_lifecycle'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovery_preferences',
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('body_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('class_id', 'account_id')
    )
    op.create_table('profile_consent_audit',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_consent_audit_account_id'), 'profile_consent_audit', ['account_id'], unique=False)
    op.create_index(op.f('ix_profile_consent_audit_class_id'), 'profile_consent_audit', ['class_id'], unique=False)
    op.create_table('shared_profiles',
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('body_json', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('class_id', 'account_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_profiles')
    op.drop_index(op.f('ix_profile_consent_audit_class_id'), table_name='profile_consent_audit')
    op.drop_index(op.f('ix_profile_consent_audit_account_id'), table_name='profile_consent_audit')
    op.drop_table('profile_consent_audit')
    op.drop_table('discovery_preferences')
    # ### end Alembic commands ###
