"""team_profile_consent

Revision ID: 0007_team_profiles
Revises: 0006_profiles
"""
from alembic import op
import sqlalchemy as sa


revision = '0007_team_profiles'
down_revision = '0006_profiles'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_profile_consent_audit',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_profile_consent_audit_account_id'), 'team_profile_consent_audit', ['account_id'], unique=False)
    op.create_index(op.f('ix_team_profile_consent_audit_team_id'), 'team_profile_consent_audit', ['team_id'], unique=False)
    op.create_table('team_shared_profiles',
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('body_json', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discovery', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('team_id', 'account_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_shared_profiles')
    op.drop_index(op.f('ix_team_profile_consent_audit_team_id'), table_name='team_profile_consent_audit')
    op.drop_index(op.f('ix_team_profile_consent_audit_account_id'), table_name='team_profile_consent_audit')
    op.drop_table('team_profile_consent_audit')
    # ### end Alembic commands ###
