"""class and project lifecycle

Revision ID: cc1c2083e10b
Revises: 0004_openings
"""
from alembic import op
import sqlalchemy as sa


revision = '0005_lifecycle'
down_revision = '0004_openings'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('courses', sa.Column('creator_id', sa.String(36), nullable=True))
    op.create_foreign_key('fk_course_creator', 'courses', 'accounts', ['creator_id'], ['id'])
    op.execute('UPDATE courses SET creator_id = organizer_id')
    op.add_column('teams', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'archived_at')
    op.drop_column('courses', 'archived_at')
    op.drop_constraint('fk_course_creator', 'courses', type_='foreignkey')
    op.drop_column('courses', 'creator_id')
    # ### end Alembic commands ###
